apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jbrr-infisical-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: infisical-store
  target:
    name: jbrr-infisical-secrets
  dataFrom:
  - find:
      name:
        regexp: ".*"