apiVersion: v1
kind: Secret
metadata:
  name: infisical-auth
type: Opaque
stringData:
  clientId: {{ (index .Values "external-secrets").secretstores.infisical.clientId }}
  clientSecret: {{ (index .Values "external-secrets").secretstores.infisical.clientSecret }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: infisical-store
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: beproeving
            name: infisical-auth
          clientSecret:
            key: clientSecret
            name: infisical-auth
            namespace: beproeving
      secretsScope:
        projectSlug: {{ (index .Values "external-secrets").secretstores.infisical.projectSlug }}
        environmentSlug: dev
        secretsPath: /
        recursive: false
        expandSecretReferences: true