apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: jbrr-store
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-reader
      remoteNamespace: jbrr
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt