apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowable-rest.fullname" . }}
  labels:
    {{- include "flowable-rest.labels" . | nindent 4 }}
stringData:
  FLOWABLE_REST_APP_ADMIN_PASSWORD: {{ .Values.admin.password | quote }}
  FLOWABLE_REST_APP_ADMIN_USER: {{ .Values.admin.user | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.user | quote }}

