image:
  name: ghcr.io/infonl/vng-referentielijsten
  tag: "0.6.1"
  pullPolicy: IfNotPresent

database:
  host: ""
  name: ""
  user: ""
  password: ""

secretKey: ""

nodeSelector: { }

tolerations: [ ]

affinity: { }
