apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bm.name" . }}-config
  labels:
    app.kubernetes.io/instance: {{ .Values.instance }}
    app.kubernetes.io/name: {{ include "bm.name" . }}-config
    {{- include "bm.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: "Release"
  ASPNETCORE_URLS: "http://+:{{ .Values.service.port }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bm.name" . }}-serviceaccount
  labels:
    app.kubernetes.io/instance: {{ .Values.instance }}
    app.kubernetes.io/name: {{ include "bm.name" . }}-serviceaccount
    {{- include "bm.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bm.name" . }}-brp-personen-mock
  labels:
    app.kubernetes.io/instance: {{ .Values.instance }}
    app.kubernetes.io/name: {{ include "bm.name" . }}-brp-personen-mock
    {{- include "bm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http-brp-mock
      port: {{ .Values.service.port }}
      targetPort: http-brp-mock
      protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ .Values.instance }}