apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bm.name" . }}-config
  labels:
    app.kubernetes.io/instance: {{ .Values.instance }}
    app.kubernetes.io/name: {{ include "bm.name" . }}-config
    {{- include "bm.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: "Release"
  ASPNETCORE_URLS: "http://+:{{ .Values.service.port }}"
