apiVersion: v1
data:
  ASPNETCORE_ENVIRONMENT: Release
  ASPNETCORE_URLS: http://+:5010
kind: ConfigMap
metadata:
  name: {{ include "brppersonenmock.name" . }}
  labels:
    {{- include "brppersonenmock.labels" . | nindent 4 }}