apiVersion: apps/v1
kind: Deployment
metadata:
  name: brp-personen-mock
  labels:
    app.kubernetes.io/instance: podiumd
    app.kubernetes.io/name: brp-personen-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: podiumd
      app.kubernetes.io/name: brp-personen-mock
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: podiumd
        app.kubernetes.io/name: brp-personen-mock
    spec:
      serviceAccount: brp-personen-mock
      serviceAccountName: brp-personen-mock
      containers:
        - name: brp-personen-mock
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap }}
          ports:
            - name: http-brp-mock
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
