apiVersion: v1
kind: Service
metadata:
  name: brp-personen-mock
  labels:
    app.kubernetes.io/instance: podiumd
    app.kubernetes.io/name: brp-personen-mock
spec:
  type: ClusterIP
  ports:
    - name: http-brp-mock
      port: 5010
      targetPort: http-brp-mock
      protocol: TCP
  selector:
    app.kubernetes.io/instance: podiumd
