apiVersion: apps/v1
kind: Deployment
metadata:
  name: brp-personen-mock
  labels:
    app.kubernetes.io/instance: podiumd
    app.kubernetes.io/name: brp-personen-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: podiumd
      app.kubernetes.io/name: brp-personen-mock
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: podiumd
        app.kubernetes.io/name: brp-personen-mock
    spec:
      {{- with .Values.brppersonenmock.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccount: brp-personen-mock
      serviceAccountName: brp-personen-mock
      containers:
        - name: brp-personen-mock
          image: "{{ .Values.brppersonenmock.image.repository }}:{{ .Values.brppersonenmock.image.tag }}"
          imagePullPolicy: {{ .Values.brppersonenmock.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: brp-personen-mock
          ports:
            - name: http-brp-mock
              containerPort: 5010
              protocol: TCP
      restartPolicy: Always
      {{- with .Values.brppersonenmock.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.brppersonenmock.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.brppersonenmock.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}