apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bm.name" . }}-brp-personen-mock
  labels:
    app.kubernetes.io/instance: {{ .Values.instance }}
    app.kubernetes.io/name: {{ include "bm.name" . }}-brp-personen-mock
    {{- include "bm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.instance }}
      app.kubernetes.io/name: {{ include "bm.name" . }}-brp-personen-mock
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Values.instance }}
        app.kubernetes.io/name: {{ include "bm.name" . }}-brp-personen-mock
        {{- include "bm.labels" . | nindent 8 }}
    spec:
      serviceAccount: {{ .Values.serviceAccount }}
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
        - name: brp-personen-mock
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap }}
          ports:
            - name: http-brp-mock
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
