apiVersion: v1
kind: Service
metadata:
  name: {{ include "bm.name" . }}-brp-personen-mock
  labels:
    app.kubernetes.io/instance: {{ .Values.instance }}
    app.kubernetes.io/name: {{ include "bm.name" . }}-brp-personen-mock
    {{- include "bm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http-brp-mock
      port: {{ .Values.service.port }}
      targetPort: http-brp-mock
      protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ .Values.instance }}