apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bm.name" . }}-serviceaccount
  labels:
    app.kubernetes.io/instance: {{ .Values.instance }}
    app.kubernetes.io/name: {{ include "bm.name" . }}-serviceaccount
    {{- include "bm.labels" . | nindent 4 }}
