apiVersion: v1
kind: ConfigMap
metadata:
  name: brp-personen-mock
  labels:
    app.kubernetes.io/instance: podiumd
    app.kubernetes.io/name: brp-personen-mock
data:
  ASPNETCORE_ENVIRONMENT: "Release"
  ASPNETCORE_URLS: "http://+:5010"
