apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vrl.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "vrl.name" . }}
    {{- include "vrl.labels" . | nindent 4 }}
data:
  db-host: {{ required ".Values.database.host is required" .Values.database.host  | quote}}
  db-name: {{ required ".Values.database.name is required" .Values.database.name  | quote}}
  db-user: {{ required ".Values.database.user is required" .Values.database.user  | quote}}
