image:
  # -- Personen mock image repository
  repository: ghcr.io/brp-api/personen-mock
  # -- Personen mock tag
  tag: 2.7.0-202508211438
  # -- Personen mock image pull policy
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5010
serviceAccount:
  automount: true
  create: true
  annotations: {}
  name: "brp-personen-mock"
imagePullSecrets: []
nodeSelector: {}
affinity: {}
tolerations: []
resources:
  requests:
  # -- Personen mock container requests and limits
    cpu: 10m
    memory: 150Mi
nameOverride: "brp-personen-mock"
