{
 "title": "Logging Maykin components",
 "description": "Open Forms, Open Zaak, Open Notificaties and Objects API logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Component",
    "query": {}
   },
   {
    "name": "subapp",
    "label": "Subcomponent",
    "query": {}
   },
   { "name": "search", "label": "Zoeken" },
   {
    "name": "excluded_log_levels",
    "query": "DEBUG, INFO, maykin, maykinmedia, Datadog, sentry, NO MERCY, token, secret, connectionid, admin, root, user, username, password, pwd, apikey, authorization, bearer, client_id, client_secret"
   }
  ]
 },
 "panels": [
  { "title": "Open Forms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Missing registrations rate",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "1 - (\n  sum(\n    count_over_time(\n      {app=\"openformulieren-worker\"}\n      | json\n      | event=\"registration_success\"\n      | action=\"registrations.main_registration\"\n      [$__range]\n    )\n  ) or vector(0)\n) / sum(\n  count_over_time(\n    {app=\"openformulieren\"}\n    | json\n    | event=\"submission_completed\"\n    [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Submission count",
   "type": "stat",
   "description": "The total number of completed form submissions",
   "gridPos": { "h": 11, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"openformulieren\"}\n        | json \n        | event = `submission_completed` \n        [$__range]\n    )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Registered submission count",
   "type": "stat",
   "description": "The total number of successfully registered form submissions",
   "gridPos": { "h": 11, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"openformulieren-worker\"}\n        | json \n        | event = `registration_success` \n        | action = `registrations.main_registration`\n        [$__range]\n    )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Registered submissions",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"openformulieren-worker\"} \n| json \n| action=\"registrations.main_registration\", event=\"registration_success\""
    }
   ]
  },
  {
   "title": "Failures",
   "type": "table",
   "description": "Detected registration failures",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"openformulieren-worker\"} | json | event=\"registration_failure\" | trigger = \"on_completion\""
    }
   ]
  },
  { "title": "Open Zaak", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Failed requests to create zaken",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "1 - (\n  sum(\n    count_over_time(\n      {app=\"openzaak\"}\n      | json\n      | event=\"zaak_created\"\n      [$__range]\n    )\n  ) or vector(0)\n) / sum(\n  count_over_time(\n    {app=\"openzaak\"}\n        | json \n        | event = \"request\" \n        | source = \"uwsgi\" \n        | method = \"POST\"\n        | path = \"/zaken/api/v1/zaken\"\n    [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Requests to create zaak",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 5, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"openzaak\"}\n        | json \n        | event = \"request\" \n        | source = \"uwsgi\" \n        | method = \"POST\"\n        | path = \"/zaken/api/v1/zaken\"\n        [$__range]\n    )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Successfully created zaken",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"openzaak\"}\n        | json \n        | event = `zaak_created` \n        [$__range]\n    )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Created zaken in Open Zaak",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"openzaak\"} | json | event=\"zaak_created\""
    }
   ]
  },
  {
   "title": "Failures",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"openzaak\"}\n| json\n| event = \"request_finished\"\n| request !~ `GET .*` \n| event = `request_finished` \n| code =~ `[4-5].*`"
    }
   ]
  },
  { "title": "Objects API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Failed requests to create objects",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "1 - (\n  sum(\n    count_over_time(\n      {app=\"objecten\"}\n      | json\n      | event=\"object_created\"\n      [$__range]\n    )\n  ) or vector(0)\n) / sum(\n  count_over_time(\n    {app=\"objecten\"}\n        | json \n        | event = \"request\" \n        | source = \"uwsgi\" \n        | method = \"POST\"\n        | path = \"/api/v2/objects\"\n    [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Requests to create objects",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 5, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"objecten\"}\n        | json \n        | event = \"request\" \n        | source = \"uwsgi\" \n        | method = \"POST\"\n        | path = \"/api/v2/objects\"\n        [$__range]\n    )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Successfully created objects",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"objecten\"}\n        | json \n        | event = `object_created` \n        [$__range]\n    )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Created objects",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 42 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"objecten\"} | json | event = \"object_created\""
    }
   ]
  },
  {
   "title": "Failures",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 53 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"objecten\"}\n| json\n| event = \"request_finished\"\n| request = \"POST /api/v2/objects\"\n| code >= 400"
    }
   ]
  },
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Notifications received from applications",
   "type": "stat",
   "description": "Notifications received from Open Zaak and Objects API",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"opennotificaties\"}\n        | json \n        | request=\"POST /api/v1/notificaties\" \n        | event=\"request_started\"\n        [$__range]\n    )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Notifications sent to subscribers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"opennotificaties-worker\"}\n        | json \n        | task=\"nrc.api.tasks.deliver_message\" \n        | event=\"task_started\"\n        [$__range]\n    )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Notifications, successfully received by subscribers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 14, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"opennotificaties-worker\"}\n        | json \n        | event=\"notification_successful\"\n        [$__range]\n    )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Successful notifications",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"opennotificaties-worker\"}\n| json \n| event=\"notification_successful\"\n"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"opennotificaties-worker\"} \n| json \n| event=\"notification_failed\" or event=\"notification_error\"  "
    }
   ]
  },
  {
   "title": "All logs for \"$app\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 }
  },
  {
   "title": "The logs component: $app",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (app) (count_over_time({app=~\"$subapp\"}[$__interval]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Logs component: $app",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=~\"$subapp\"} |~ \"(?i)$search\" !~ `(?i)$excluded_log_levels`"
    }
   ]
  }
 ]
}