{
 "title": "Monitoring en logging (with structlog)",
 "description": "Open Forms, Open Zaak, Open Notificaties and Objects API logs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OF Submissions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"openformulieren\"}\n        |= \"submission_completed\"\n        | json event\n        | event = `submission_completed` \n        [$__range]\n    )\n) or vector(0)",
     "legendFormat": "Submissions"
    }
   ]
  },
  {
   "title": "OF success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"openformulieren-worker\"}\n        |= \"registration\"\n        | json event=\"event\", action=\"action\"\n        | event = `registration_success` \n        | action = `registrations.main_registration`\n        [$__range]\n    )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Objects success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"objecten\"}\n        |= \"object_created\"\n        | json event\n        | event = `object_created` \n        [$__range]\n    ) \n) or vector(0)"
    }
   ]
  },
  {
   "title": "Notifications success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"opennotificaties-worker\"}\n        |= \"notification_successful\"\n        | json event\n        | event=\"notification_successful\"\n        [$__range]\n    )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "OZ Zaak success ",
   "type": "stat",
   "description": "Number of successfully created zaken in Open Zaak",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"openzaak\"}\n        |= \"zaak_created\"\n        | json event\n        | event = `zaak_created` \n        [$__range]\n    ) \n) or vector(0)"
    }
   ]
  },
  {
   "title": "eSuite Zaak success",
   "type": "stat",
   "description": "Number of successfully created zaken in eSuite",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time(\n    {app=\"esuite\"} |= `ZAAK_CREATED` [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "OF fails",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (public_reference)(\n  count_over_time(\n    {app=\"openformulieren-worker\"}\n    |= \"registration\"\n    | json event=\"event\", action=\"action\", public_reference=\"public_reference\"\n    | event=\"registration_failure\"\n    | action=\"registrations.main_registration\"\n    [$__range]\n    ) \n)"
    }
   ]
  },
  {
   "title": "Objects fails",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"objecten\"}\n        |= \"POST /api/v2/objects\"\n        | json event=\"event\", request=\"request\", code=\"code\"\n        | event = \"request_finished\"\n        | request = \"POST /api/v2/objects\"\n        | code >= 400\n        [$__range]\n    ) \n) or vector(0)"
    }
   ]
  },
  {
   "title": "Notifications failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"opennotificaties-worker\"}\n        |= \"notification_\"\n        | json event\n        | event=~\"notification_failed|notification_error\"\n        [$__range]\n    )\n    \n) or vector(0)"
    }
   ]
  },
  {
   "title": "OZ Zaak fails",
   "type": "stat",
   "description": "Number of errors during zaak creation in Open Zaak",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"openzaak\"}\n        |= \"POST /zaken/api/v1/zaken\"\n        | json event=\"event\", request=\"request\", code=\"code\"\n        | event = \"request_finished\"\n        | request = \"POST /zaken/api/v1/zaken\"\n        | code >= 400\n        [$__range]\n    ) \n) or vector(0)"
    }
   ]
  },
  {
   "title": "eSuite Zaak fails",
   "type": "stat",
   "description": "Number of errors during zaak creation in eSuite",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time(\n    {app=\"esuite\"} |= `PRODUCTAANVRAAG_PROCESSING_FAILURE` [$__range]\n  )\n)"
    }
   ]
  },
  { "title": "Other numbers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "OF fails for 1h",
   "type": "stat",
   "description": "in %",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "1 - sum(\n    count_over_time (\n        {app=\"openformulieren-worker\"}\n        |= \"registration\"\n        | json event=\"event\", action=\"action\"\n        | event = `registration_success` \n        | action = `registrations.main_registration`\n        [1h]\n    )\n) / sum(\n    count_over_time (\n        {app=\"openformulieren\"}\n        |= \"submission_completed\"\n        | json event\n        | event = `submission_completed` \n        [1h]\n    )\n)"
    }
   ]
  },
  {
   "title": "OF email fails",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time(\n    {app=\"openformulieren-worker\"} \n    |= `email_status_change`\n    |= `Failed`\n    | json\n    | event=\"email_status_change\"\n    | status_label=\"Failed\"\n    [$__range]\n  )\n)\nor vector(0)\n"
    }
   ]
  },
  { "title": "Detailed summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Open Forms stats by registration plugin",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by (plugin, event) (\n  sum by (plugin, event, public_reference) (\n    count_over_time(\n      {app=\"openformulieren-worker\"}\n      |= \"registration_\"\n      | json event=\"event\", plugin=\"plugin\", public_reference=\"public_reference\", trigger=\"trigger\"\n      | event=~\"registration_failure|registration_success\"\n      [$__range]\n    )\n  )\n)"
    }
   ]
  },
  {
   "title": "Notifications by subscriber and resource",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(subscription_callback, resource) (\n  count_over_time(\n    {app=\"opennotificaties-worker\"} \n    |=\"notification_successful\"\n    | json event=\"event\", subscription_callback=\"subscription_callback\", resource=\"resource\"\n    | event=\"notification_successful\" \n    [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Requests to Open Zaak",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (path, status)(\n    count_over_time (\n        {app=\"openzaak\"}\n        |= \"request\"\n        |= \"/api/\"\n        | json event=\"event\", method=\"method\", path=\"path\", status=\"status\"\n        | event = \"request\"\n        | path=~\".*/api/.*\"\n        | method!~\"GET|HEAD\"\n        | label_format path=`{{ regexReplaceAllLiteral \"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\" .path \"<uuid>\" }}`                \n        [$__range]\n    )\n) \n\n"
    }
   ]
  },
  {
   "title": "Open Forms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true
  },
  {
   "title": "Successes",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"openformulieren-worker\"}\n|= \"registration_success\"\n| json \n| event=\"registration_success\"\n| action=\"registrations.main_registration\""
    }
   ]
  },
  {
   "title": "Failures",
   "type": "table",
   "description": "Detected registration failures",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"openformulieren-worker\"} | json | event=\"registration_failure\""
    }
   ]
  },
  {
   "title": "Emails",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"openformulieren-worker\"} \n|= `email_status_change`\n| json"
    }
   ]
  },
  {
   "title": "Objects API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Created objects",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 114 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{app=\"objecten\"}\n|= \"object_created\"\n| json event=\"event\", object_uuid=\"object_uuid\", token_identifier=\"token_identifier\"\n| event = \"object_created\""
      }
     ]
    },
    {
     "title": "Failures",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 120 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{app=\"objecten\"}\n| json event=\"event\", request=\"request\", code=\"code\", request_id=\"request_id\", title=\"title\"\n| event=\"request_finished\"\n| request=\"POST /api/v2/objects\"\n| code >= 400"
      }
     ]
    },
    {
     "title": "All errors in Objects API",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 129 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{app=\"objecten\"}\n| json\n| event=\"api.handled_exception\"\n| status >= 400"
      }
     ]
    }
   ]
  },
  {
   "title": "Open Notificaties",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful notifications",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{app=\"opennotificaties-worker\"}\n|= \"notification_successful\"\n| json  event=\"event\", subscription_callback=\"subscription_callback\", channel_name=\"channel_name\", action=\"action\", resource=\"resource\", resource_url=\"resource_url\"\n| event=\"notification_successful\"\n"
      }
     ]
    },
    {
     "title": "Failures",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{app=\"opennotificaties-worker\"}\n|= \"notification_\"\n| json event=\"event\", resource=\"resource\", action=\"action\", resource_url=\"resource_url\", subscription_callback=\"subscription_callback\", channel_name=\"channel_name\", task_attempt_count=\"task_attempt_count\", http_status_code=\"http_status_code\"\n| event=~\"notification_failed|notification_error\""
      }
     ]
    }
   ]
  },
  {
   "title": "Open Zaak",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "panels": [
    {
     "title": "Successes (created zaken)",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{app=\"openzaak\"} \n|= \"zaak_created\"\n| json event=\"event\", identificatie=\"identificatie\", zaaktype=\"zaaktype\"\n| event=\"zaak_created\""
      }
     ]
    },
    {
     "title": "Failures",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{app=\"openzaak\"}\n|= \"POST /zaken/api/v1/zaken\"\n| json event=\"event\", request=\"request\", code=\"code\", request_id=\"request_id\"\n| event = \"request_finished\"\n| request = \"POST /zaken/api/v1/zaken\"\n| code >= 400"
      }
     ]
    }
   ]
  },
  {
   "title": "eSuite",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "panels": [
    {
     "title": "Successes",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{app=\"esuite\"} \n|= `ZAAK_CREATED`\n| json"
      }
     ]
    },
    {
     "title": "Failures",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{app=\"esuite\"} \n|= `PRODUCTAANVRAAG_PROCESSING_FAILURE`\n| json"
      }
     ]
    }
   ]
  }
 ]
}