{
 "title": "Logging experimental",
 "description": "Dashboard shows interactions between applications",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "ZAC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ontvangen notificaties ZAC",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time (\n        {app=\"zac\"}\n        |~ \"action=CREATE\"\n        |~ \"resource=ZAAKINFORMATIEOBJECT\"\n        |~ \"channel=ZAKEN\"\n        |~ \"nl.info.zac.notification.NotificationReceiver\" \n        [$__range]\n    )\n) \n",
     "legendFormat": "channel = ZAKEN, resource = ZAAKINFORMATIEOBJECT"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time (\r\n        {app=\"zac\"}\r\n        |~ \"action=CREATE\"\r\n        |~ \"resource=INFORMATIEOBJECT\"\r\n        |~ \"channel=INFORMATIEOBJECTEN\"\r\n        |~ \"nl.info.zac.notification.NotificationReceiver\"\r\n        [$__range]\r\n    )\r\n) ",
     "legendFormat": "channel = INFORMATIEOBJECTEN, resource= INFORMATIEOBJECT"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time (\r\n        {app=\"zac\"}\r\n        |~ \"action=CREATE\"\r\n        |~ \"resource=ZAAK\"\r\n        |~ \"channel=ZAKEN\"\r\n        |~ \"nl.info.zac.notification.NotificationReceiver\" \r\n        [$__range]\r\n    )\r\n) ",
     "legendFormat": "channel = ZAKEN, resource = ZAKEN"
    }
   ]
  },
  { "title": "Open Zaak", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Keten formulieren -> Open Zaak",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"objecten\"}\n        | json \n        | event = `object_created` \n        [$__range]\n    )\n) or vector(0)",
     "legendFormat": "Aangemaakte objecten"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n    count_over_time (\r\n        {app=\"opennotificaties-worker\"}\r\n        | json \r\n        | event=\"notification_successful\"\r\n        [$__range]\r\n    )\r\n) or vector(0)",
     "legendFormat": "Gestuurde notificaties"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n    count_over_time (\r\n        {app=\"openformulieren\"}\r\n        | json \r\n        | event = `submission_completed` \r\n        [$__range]\r\n    )\r\n) or vector(0)",
     "legendFormat": "Ingezonden formulieren"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n    count_over_time (\r\n        {app=\"openformulieren-worker\"}\r\n        | json \r\n        | event = `registration_success` \r\n        | action = `registrations.main_registration`\r\n        [$__range]\r\n    )\r\n) or vector(0)",
     "legendFormat": "Succesvol geregistreerde formulieren"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n    count_over_time (\r\n        {app=\"openzaak\"}\r\n        | json \r\n        | event = `zaak_created` \r\n        [$__range]\r\n    )\r\n) or vector(0)",
     "legendFormat": "Aangemaakte zaken"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time (\r\n        {app=\"zac\"}\r\n        |~ \"action=CREATE\"\r\n        |~ \"nl.info.zac.notification.NotificationReceiver\"\r\n        [$__range]\r\n    )\r\n) or vector(0)",
     "legendFormat": "Ontvangen notificaties ZAC"
    }
   ]
  },
  { "title": "Open Forms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Successful submissions",
   "type": "stat",
   "description": "Only registered submissions",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"openformulieren-worker\"}\n        | json \n        | event = `registration_success` \n        | action = `registrations.main_registration`\n        [$__range]\n    )\n) "
    }
   ]
  },
  {
   "title": "Failed submissions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (public_reference)(\n  count_over_time(\n    {app=\"openformulieren-worker\"}\n    | json\n    | event=\"registration_failure\"\n    | action=\"registrations.main_registration\"\n    [$__range]\n    ) \n)\n"
    }
   ]
  },
  {
   "title": "Registration plugins",
   "type": "barchart",
   "description": "Failed numbers can be duplicated due to repeated attempts",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(plugin, event) (\n  count_over_time(\n    {app=\"openformulieren-worker\"} \n    | json \n    | event=~\"registration_failure|registration_success\" \n    | trigger!=\"on_retry\"\n    |__error__=``\n    [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Alle inzendingen en totaal aantal sucesvolle inzendingen in % formulieren",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"openformulieren\"}\n        | json \n        | event = `submission_completed` \n        [$__range]\n    )\n) or vector(0)",
     "legendFormat": "Ingezonden formulieren"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n    count_over_time (\r\n        {app=\"openformulieren-worker\"}\r\n        | json \r\n        | event = `registration_success` \r\n        | action = `registrations.main_registration`\r\n        [$__range]\r\n    )\r\n) or vector(0)",
     "legendFormat": "Succesvol geregistreerd"
    }
   ]
  },
  {
   "title": "Successful zaak creation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"openzaak\"}\n        | json \n        | event = `zaak_created` \n        [$__range]\n    )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Failed zaak creation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"openzaak\"}\n        | json \n        | event = \"request\" \n        | source = \"uwsgi\" \n        | method = \"POST\"\n        | path = \"/zaken/api/v1/zaken\"\n        [$__range]\n    )\n) \n- sum(\n    count_over_time (\n        {app=\"openzaak\"}\n        | json \n        | event = `zaak_created` \n        [$__range]\n    )\n) \n",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requests to Open Zaak",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (request, code)(\n    count_over_time (\n        {app=\"openzaak\"}\n        | json \n        | event = \"request_finished\"         \n        [$__range]\n    )\n) \n"
    }
   ]
  },
  {
   "title": "Successful document creation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"openzaak\"}\n        | json \n        | event = `enkelvoudiginformatieobject_created` \n        [$__range]\n    )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Failed document creation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time (\n        {app=\"openzaak\"}\n        | json \n        | event = \"request\" \n        | source = \"uwsgi\" \n        | method = \"POST\"\n        | path = \"/documenten/api/v1/enkelvoudiginformatieobjecten\"\n        [$__range]\n    )\n) \n- sum(\n    count_over_time (\n        {app=\"openzaak\"}\n        | json \n        | event = `enkelvoudiginformatieobject_created` \n        [$__range]\n    )\n) "
    }
   ]
  },
  {
   "title": "HTTP codes",
   "type": "timeseries",
   "description": "Exclude HTTP GET and HEAD methods ",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 43 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (code, request)(\n    count_over_time (\n        {app=\"openzaak\"}\n        | json \n        | code = \"201\"\n        | event = \"request_finished\"\n        | request !~ \"GET .*\"\n        | request !~ \"HEAD .*\"\n        [$__interval]\n    )\n) \n",
     "legendFormat": "Success - {{request}} "
    },
    {
     "direction": "backward",
     "expr": "sum by (code, request)(\r\n    count_over_time (\r\n        {app=\"openzaak\"}\r\n        | json \r\n        | code !~ \"201\"\r\n        | event = \"request_finished\"\r\n        | request !~ \"GET .*\"\r\n        | request !~ \"HEAD .*\"\r\n        [$__interval]\r\n    )\r\n) \r\n",
     "legendFormat": "Error - {{request}}"
    }
   ]
  }
 ]
}