{
 "title": "Monitoring",
 "description": "Blackbox exporter HTTP prober dashboard",
 "tags": [
  "blackbox",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(probe_success, job)"
   },
   {
    "name": "group",
    "label": "Naam",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\"},group)"
    }
   },
   {
    "name": "subgroup",
    "label": "Type",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\", group=~\"$group\"},subgroup)"
    }
   },
   {
    "name": "instance",
    "label": "Link",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\"},instance)"
    }
   },
   { "name": "datasource", "query": "Prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"apiserver\"},cluster)"
    }
   },
   {
    "name": "instance1",
    "label": "instance1",
    "query": {
     "query": "label_values(up{job=~\"apiserver\", cluster=~\"$cluster\"},instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster1\", job=\"kubelet\", metrics_path=\"/metrics\"},namespace)"
    }
   },
   {
    "name": "cluster1",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster1\", job=\"kubelet\", metrics_path=\"/metrics\"},namespace)"
    }
   },
   {
    "name": "volume",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster1\", job=~\"kubelet\", metrics_path=~\"/metrics\", namespace=~\"$namespace\"},persistentvolumeclaim)"
    }
   },
   { "name": "job1", "query": { "query": "label_values(job)" } },
   {
    "name": "k8s_version",
    "query": {
     "query": "label_values(kube_node_info,kubelet_version)"
    }
   },
   { "name": "deployment", "query": ".*" },
   {
    "name": "list_threshold",
    "label": "Certificaten die verlopen over minder dan (dagen)",
    "query": "1,7,15,30,50,60,90,180,365,730,1095,1460,1825,3650,7300"
   },
   { "name": "Filters" },
   {
    "name": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "chart",
    "query": {
     "query": "label_values(helm_chart_info,chart)"
    }
   },
   {
    "name": "appVersion",
    "query": {
     "query": "label_values(helm_chart_info,appVersion)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(helm_chart_info,version)"
    }
   },
   {
    "name": "release",
    "query": {
     "query": "label_values(helm_chart_info,release)"
    }
   },
   {
    "name": "revision",
    "query": {
     "query": "label_values(helm_chart_info,revision)"
    }
   },
   {
    "name": "namespace2",
    "query": {
     "query": "label_values(helm_chart_info,namespace)"
    }
   },
   { "name": "versie_dashboard", "query": "1.1" }
  ]
 },
 "panels": [
  {
   "title": "Totaal dashboards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "grafana_stat_totals_dashboard", "legendFormat": "__auto" }
   ]
  },
  { "title": "Helm charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Helm charts",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "min(helm_chart_info{chart=~\"$chart\", namespace=~\"$namespace2\", release=~\"$release\", appVersion=~\"$appVersion\", version=~\"$version\", revision=~\"$revision\"}) by (chart, release, namespace, version, appVersion, revision) != 2",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Deployments",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=~\"$deployment\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "StatefulSets",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_available{deployment=~\"$deployment\"}",
     "legendFormat": "{{ statefulset}}"
    }
   ]
  },
  {
   "title": "ReplicaSets",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "kube_replicaset_status_ready_replicas",
     "legendFormat": "{{replicaset}}"
    }
   ]
  },
  {
   "title": "DaemonSets",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_ready{deployment=~\"$deployment\"}",
     "legendFormat": "{{daemonset}}"
    }
   ]
  },
  {
   "title": "Pod",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Versienummers componenten",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Grafana versie",
     "type": "table",
     "gridPos": { "h": 4, "w": 23, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "grafana_build_info{job=~\"$job1\"}"
      }
     ]
    },
    {
     "title": "Kubernetes cluster version",
     "type": "text",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
     "options": {
      "content": "<div class=\"text-center\">\n  <img style=\"height:80px\" src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Kubernetes_logo_without_workmark.svg/1200px-Kubernetes_logo_without_workmark.svg.png\">\n  <h2 style=\"padding-top:20px\">$k8s_version</h2>\n</div>"
     }
    },
    {
     "title": "Grafana Version",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "grafana_build_info{cluster=~\"$cluster\"}",
       "legendFormat": "{{ version }}"
      }
     ]
    },
    {
     "title": "Prometheus Version",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "Prometheus_build_info {cluster=~\"$cluster\"}",
       "legendFormat": "{{ version }}"
      }
     ]
    },
    {
     "title": "Prometheus Operator Version",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "Prometheus_operator_build_info{cluster=~\"$cluster\"}",
       "legendFormat": "{{ version }}"
      }
     ]
    },
    {
     "title": "Node Ubuntu OS Version",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_os_version", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Loki Version",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "loki_build_info" }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    { "title": "Summary of alerts status", "type": "alertlist", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 } },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(alertmanager_alerts_received_total{status=\"resolved\"}) OR vector(0)",
       "legendFormat": "Resolved alerts"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(ALERTS{severity=\"critical\"}) or vector(0)",
       "legendFormat": "Critical alert"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 8, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(ALERTS{severity=\"warning\"}) OR vector(0)",
       "legendFormat": "Warning alert"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(ALERTS{severity=\"info\"}) OR vector(0)",
       "legendFormat": "Info alert"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{severity=\"critical\"}) OR vector(0)",
       "legendFormat": "Critical alerts"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{severity=\"warning\"}) OR vector(0)",
       "legendFormat": "Warning alerts"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(ALERTS{severity=\"info\"}) OR vector(0)",
       "legendFormat": "Info alerts"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP status code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Status code",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 5, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_values('value',probe_http_status_code{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'})",
       "legendFormat": "http status {{ value }}"
      }
     ]
    },
    {
     "title": "probe success / failure",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 5, "x": 5, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " count_values('value',probe_success{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'})",
       "legendFormat": "{{ value }}"
      }
     ]
    },
    {
     "title": "probe success / failure",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (probe_http_status_code{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'} - 0 == 200)",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "sum by (instance) (probe_http_status_code{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'} - 0 != 200)",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Beschikbaarheid Kubernetes Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Server - Health Status",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"apiserver\", cluster=~\"$cluster\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Availability (30d) > 99.000%",
     "type": "stat",
     "description": "How many percent of requests (both read and write) in 30 days have been answered successfully and fast enough?",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apiserver_request:availability30d{verb=\"all\", cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Write Availability (30d)",
     "type": "stat",
     "description": "How many percent of write requests (POST|PUT|PATCH|DELETE) in 30 days have been answered successfully and fast enough?",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apiserver_request:availability30d{verb=\"write\", cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Read Availability (30d)",
     "type": "stat",
     "description": "How many percent of read requests (LIST,GET) in 30 days have been answered successfully and fast enough?",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apiserver_request:availability30d{verb=\"read\", cluster=\"$cluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Services",
     "type": "table",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "probe_success{group=~\"Services|flink_taskmanager|ignite|gateway|mysql|nacos|nginx|streamtau|uumsx\"}",
       "legendFormat": "{{ group }}-{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "SSL certificaten",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Totaal certificaten",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 96 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(probe_success{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'})"
      }
     ]
    },
    {
     "title": "Failed certificaten",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 96 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(probe_success{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'} == 0)"
      }
     ]
    },
    {
     "title": "Certificaten",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "probe_success{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'}"
      },
      {
       "expr": "probe_http_ssl{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'} > 0"
      },
      {
       "expr": "sort(((probe_ssl_earliest_cert_expiry{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'}- time()) / 84600) < $list_threshold)"
      },
      {
       "expr": "probe_http_status_code{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'} > 0"
      },
      {
       "expr": "avg_over_time(probe_duration_seconds{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'}[1m])"
      },
      {
       "expr": "probe_tls_version_info{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'}"
      },
      {
       "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'}[1m])"
      },
      {
       "expr": "probe_ssl_earliest_cert_expiry{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'} * 1000"
      },
      {
       "expr": "probe_ssl_last_chain_info{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'}"
      },
      {
       "expr": "probe_http_duration_seconds{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance', phase=\"resolve\"}"
      },
      {
       "expr": "probe_http_duration_seconds{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance', phase=\"connect\"}"
      },
      {
       "expr": "probe_http_duration_seconds{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance', phase=\"tls\"}"
      },
      {
       "expr": "probe_http_duration_seconds{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance', phase=\"processing\"}"
      },
      {
       "expr": "probe_http_duration_seconds{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance', phase=\"transfer\"}"
      }
     ]
    },
    {
     "title": "Globale status SSL certificaten",
     "type": "table",
     "gridPos": { "h": 12, "w": 18, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "probe_success{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'} - 0 "
      },
      {
       "expr": "probe_http_status_code{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'} - 0"
      },
      {
       "expr": "probe_http_ssl{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'} - 0"
      },
      {
       "expr": "sort(((probe_ssl_earliest_cert_expiry{job=\"$job\", group=~'$group', group!~\"Services\",subgroup=~\"$subgroup\", instance=~'$instance'}- time()) / 84600) < $list_threshold)"
      }
     ]
    }
   ]
  },
  {
   "title": "Certificaten in Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kubernetes Secrets (time left < $list_threshold days)",
     "type": "table",
     "description": "Because of a missing feature in Grafana, critical and warning thresholds from dashboard variables will not affect coloration of the Time Left column in this table.\n\nThresholds are to be set manually in the Overrides settings for this widget.\n\nPlease vote or contribute to issue : https://github.com/grafana/grafana/issues/922",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "sort(((x509_cert_not_after{secret_name!=\"\"} - time()) / 86400) < $list_threshold)"
      }
     ]
    }
   ]
  }
 ]
}