apiVersion: v2
name: grafana
version: 8.10.1
appVersion: 11.5.2
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.com
icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
sources:
  - https://github.com/grafana/grafana
  - https://github.com/grafana/helm-charts
