# Images die nieuw of gewijzigd zijn in podiumd 4.6.1 t.o.v. 4.6.0.

# Applicaties
- name: internetaakafhandeling.web
  url: ghcr.io/interne-taak-afhandeling/internetaakafhandeling.web
  version: "3.0.0"
  digest: "sha256:b073aa8755793e7f7abf7bb3ab28454b2aff9089ecfd245580d73fa01de13740"
- name: internetaakafhandeling.poller
  url: ghcr.io/interne-taak-afhandeling/internetaakafhandeling.poller
  version: "3.0.0"
  digest: "sha256:bd802f55d3365c3ccd95bd495aed6e2416630be9164aeef2322503c5ddb20629"
- name: openinwoner
  url: docker.io/maykinmedia/open-inwoner
  version: "2.1.1"
  digest: "sha256:07361a6b2037c5a0fcfe4b0e08d09603c4ffbe621c0a4e5fe50f40f6bad65097"
- name: referentielijsten
  url: docker.io/maykinmedia/referentielijsten-api
  version: "0.7.1"
  digest: "sha256:6bae71f30745e3e24f98d41254fce22fc0d5ec4277dad7647ee2d297cfcf7cf9"
- name: openbeheer
  url: docker.io/maykinmedia/open-beheer
  version: "0.9.0"
  digest: "sha256:1a11b06dadb82c992468709b1aa92d0501aef6d526a7afb52bacac6917385166"
- name: keycloak-operator
  url: quay.io/keycloak/keycloak-operator
  version: "26.5.7"
  digest: "sha256:4aaa52610f9427ef0eebbf120b24bb22cf99b7197f125b140887e2add407edce"
- name: keycloak
  url: quay.io/keycloak/keycloak
  version: "26.5.7"
  digest: "sha256:45ae20191531eb608ddb0b775d012b40d3e4f942697f3214694887dd7c108d13"

# Observability (benodigd wanneer values-enable-observability.yaml wordt gebruikt)
- name: clamav_exporter
  url: docker.io/sergeymakinen/clamav_exporter
  version: "v2.1.2"
  digest: "sha256:1bb053065ca892025928b90983d8bad638786884958e63048cd11106db9a350c"
