# Images die nieuw of gewijzigd zijn in podiumd 4.6.4 t.o.v. 4.6.3.

# Tooling
- name: k8s
  url: docker.io/alpine/k8s
  version: "1.33.10"
  digest: "sha256:84746e8ea8ba20fb702b3e1221121a511c85dfc3e47953b2d6713dcc907e4e05"

# Nginx (api-proxy en Maykin/ZAC nginx sidecars)
- name: nginx-unprivileged
  url: docker.io/nginxinc/nginx-unprivileged
  version: "1.29.8"
  digest: "sha256:49b1dda3714696e4930e5cd419ede1c62f3fdc64e98ff636b201966f17e0b9a2"
