# Images die nieuw of gewijzigd zijn in podiumd 4.6.2 t.o.v. 4.6.1.

# Applicaties
- name: kubectl
  url: registry.k8s.io/kubectl
  version: "v1.33.0"
  digest: "sha256:f34045623d83213df513fe9b395b793ebe29941bf3836e3496bd3600ae7677ee"

# PABC
- name: pabc
  url: ghcr.io/platform-autorisatie-beheer-component/pabc-api
  version: "1.1.0"
  digest: "sha256:66e83416f41d546eba8b6a7f2ea061da2d293fab6b9e22f129934127f4c31b3d"

- name: pabc_migrations
  url: ghcr.io/platform-autorisatie-beheer-component/pabc-migrations
  version: "1.1.0"
  digest: "sha256:0f73051e64ebcd6ac5c169630fde4cb7ef3a39376ffb840e407158728685f83c"

- name: pabc_wait_for
  url: ghcr.io/groundnuty/k8s-wait-for
  version: "v2.0"
  digest: "sha256:c14d7271e4013b24b34ef0d7144c4610577d0e9110ccc26b163fa28089fa1f4e"

# Nginx (api-proxy gewijzigd van nginx naar nginx-unprivileged)
- name: nginx-unprivileged
  url: docker.io/nginxinc/nginx-unprivileged
  version: "1.29.5"
  digest: "sha256:5c8946de2a79b6031975ff6c54594a26bdb2f1b5abab1c03f501575ebb02510f"
