# Images die nieuw of gewijzigd zijn in podiumd 4.6.1 t.o.v. 4.6.0.

# Applicaties
- name: internetaakafhandeling.web
  url: ghcr.io/interne-taak-afhandeling/internetaakafhandeling.web
  version: "3.0.0"
  digest: "sha256:b073aa8755793e7f7abf7bb3ab28454b2aff9089ecfd245580d73fa01de13740"
- name: internetaakafhandeling.poller
  url: ghcr.io/interne-taak-afhandeling/internetaakafhandeling.poller
  version: "3.0.0"
  digest: "sha256:bd802f55d3365c3ccd95bd495aed6e2416630be9164aeef2322503c5ddb20629"

# Observability (benodigd wanneer values-enable-observability.yaml wordt gebruikt)
- name: sergeymakinen/clamav_exporter
  url: docker.io/sergeymakinen/clamav_exporter
  version: "v2.1.2"
  digest: "sha256:1bb053065ca892025928b90983d8bad638786884958e63048cd11106db9a350c"
