apiVersion: v2
name: promtail
description: Promtail is an agent which ships the contents of local logs to a Loki
  instance
appVersion: 3.0.0
version: 6.16.6
type: application
home: https://grafana.com/loki
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
sources:
- https://github.com/grafana/loki
- https://grafana.com/oss/loki/
- https://grafana.com/docs/loki/latest/
