---
# https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
config:
  logLevel: warn
  # -- publish data to loki
  clients:
    - url: http://loki-gateway/loki/api/v1/push
      tenant_id: 1 
image:
  registry: REP_ACR_NAME_REP.azurecr.io
  # Repository name for the Promtail image
  repository: promtail
  # Image tag version
  tag: "3.0.0"
resources:
  requests:
    # Minimum CPU allocation
    cpu: 50m
    # Minimum memory allocation
    memory: 96Mi
  limits:
    # Maximum CPU allocation
    cpu: 100m
    # Maximum memory allocation
    memory: 256Mi
