promtail:
  config:
    logLevel: warn
  # -- publish data to loki
    clients:
      - url: http://{{ .Release.Name }}-gateway/loki/api/v1/push
        tenant_id: 1 
  image:
    registry: ""
    # Repository name for the Promtail image
    repository: ""
    # Image tag version
    tag: ""
  resources:
    requests:
      # Minimum CPU allocation
      cpu: 50m
      # Minimum memory allocation
      memory: 96Mi
    limits:
      # Maximum CPU allocation
      cpu: 100m
      # Maximum memory allocation
      memory: 256Mi
