# zgw-office-addin:
#   enabled: true
#   fullnameOverride: "zgw-office-addin"
#   frontend:
#     # ghcr.io/infonl/zgw-office-add-in-frontend:v0.0.205
#     image:
#       tag: v0.0.205
#     # the public url where manifest.xml and static js files are served
#     frontendUrl: http://office-addin.example.com
#     # by default this is not needed as it is proxied by the frontend host
#     backendPublicUrl: ""
#     # can be enabled if needed, if for instance you don't want an ingress
#     enableHttps: false
#   backend:
#     # ghcr.io/infonl/zgw-office-add-in-backend:
#     image:
#       tag: v0.0.205
#     # secret used to generate and validate JWT tokens
#     jwtSecret: "YOUR_SECRET_KEY"
#     # the base url of the openzaak api's
#     apiBaseUrl: "http://openzaak.example.com"

# Global PostgreSQL configuration
postgresql:
  enabled: true
  # image:
  #   repository: bitnamilegacy/postgresql
  auth:
    username: "postgres"
    password: "SECRET__SECRET__SECRET"
    database: "ita"
    postgresPassword: "SECRET__SECRET__SECRET"
  # primary:
  #   persistence:
  #     enabled: true
  #     size: 8Gi
  # metrics:
  #   enabled: false
  #   image:
  #     repository: bitnamilegacy/postgres-exporter
  # volumePermissions:
  #   image:
  #     repository: bitnamilegacy/os-shell

# Ingress Configuration
ingress:
  enabled: false

# Database Configuration
database:
  # When postgresql.enabled=true, host is auto-set to {Release.Name}-postgresql
  # Specify this host only when postgresql.enabled=false
  # host: ""
  # port: "5432"
  name: "ita"
  username: "ita"
  password: "SECRET__SECRET__SECRET"

# API Connections
apiConnections:
  openKlant:
    baseUrl: "https://ontw-openklant.dimpact.icatt.nl/klantinteracties/api/v1/"
    apiKey: "SECRET__SECRET__SECRET"
  object:
    baseUrl: "https://ontw-objecten.dimpact.icatt.nl/api/v2/"
    apiKey: "SECRET__SECRET__SECRET"
  zaakSysteem:
    baseUrl: "https://ontw-openzaak.dimpact.icatt.nl"
    clientId: "ita"
    key: "SECRET__SECRET__SECRET"

logboek:
  type: "https://ontw-objecttypen.dimpact.icatt.nl/api/v2/objecttypes/1eaa9001-aa93-466f-b920-ad9caccf115b"
  typeVersion: 1

afdeling:
  type: "https://ontw-objecttypen.dimpact.icatt.nl/api/v2/objecttypes/c8d301f9-80b8-4575-8b29-3e9431f92994"
  typeVersion: 1

groep:
  type: "https://ontw-objecttypen.dimpact.icatt.nl/api/v2/objecttypes/cbec27ac-157b-490b-b586-9e8a8f5bbb85"
  typeVersion: 1

smtp:
  host: ""
  port: "25"
  username: ""
  password: "SECRET__SECRET__SECRET"
  fromEmail: ""
  enableSsl: "true"

# Web Application Configuration
web:
  image:
    # repository: "ghcr.io/interne-taak-afhandeling/internetaakafhandeling.web"
    # tag: "1.0.0"
    pullPolicy: Always
  
  # service:
  #   type: ClusterIP
  #   port: 80
  
  # Database initialization configuration
  initContainer:
    enabled: true
    image:
      repository: "postgres"
      tag: "15"
      pullPolicy: "IfNotPresent"
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
  
  oidc:
    authority: "https://ontw-keycloak-admin.dimpact.icatt.nl/realms/podiumd"
    clientId: "ita"
    clientSecret: "SECRET__SECRET__SECRET"
    itaSystemAccessRole: "ITA-Gebruiker"
    nameClaimType: "name"
    roleClaimType: "groups"
    objectregisterMedewerkerIdClaimType: "preferred_username"
    emailClaimType: "email"
  
  # resources:
  #   logoUrl: ""
  #   faviconUrl: ""
  #   designTokensUrl: ""
  #   webFontSources: []
  
  # appsettings:
  #   setting1: ""
  #   setting2: ""

# Poller Configuration
poller:
  schedule: "*/2 * * * *"
  # schedule: "*/15 * * * *"

  
  image:
    # repository: "ghcr.io/interne-taak-afhandeling/internetaakafhandeling.poller"
    tag: "1.0.0"
    pullPolicy: Always
  
  notification:
    pollerMessage: "Poller uitgevoerd om:"
    hourThreshold: "-24"
