apiVersion: v1
kind: Secret
metadata:
  name: adapter-secret
  labels:
    {{- include "kiss.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "kiss.name" . }}-adapter-secret
stringData:
  CLIENTS__0__ID: {{ .Values.adapter.clientId | quote }}
  CLIENTS__0__SECRET: {{ .Values.adapter.secret | quote }}
  ESUITE_CLIENT_ID: {{ .Values.esuite.clientId | quote }}
  ESUITE_CLIENT_SECRET: {{ .Values.esuite.secret | quote }}
  SMOELENBOEK_TOKEN: {{ .Values.objecten.token | quote }}

