apiVersion: v1
kind: Service
metadata:
  name: {{ include "kiss.fullname" . }}-frontend
  labels:
    {{- include "kiss.labelsFrontend" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kiss.selectorLabelsFrontend" . | nindent 4 }}
