apiVersion: v1
kind: ConfigMap
metadata:
  name: kiss-config
  labels:
    {{- include "kiss.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "kiss.name" . }}-frontend-config
data:
  AFDELINGEN_BASE_URL: {{ .Values.objecten.baseUrl | quote }}
  AFDELINGEN_OBJECT_TYPE_URL: {{ printf "%s/api/v2/objecttypes/%s" .Values.objecttypen.baseUrlExtern .Values.objecttypen.afdelingUUID | quote }}
  CONTACTMOMENTEN_BASE_URL: {{ .Values.adapter.baseUrl | quote }}
  ELASTIC_BASE_URL: {{ .Values.elastic.baseUrl | quote }}
  ENTERPRISE_SEARCH_BASE_URL: {{ .Values.enterpriseSearch.baseUrl | quote }}
  GROEPEN_BASE_URL: {{ .Values.objecten.baseUrl | quote }}
  GROEPEN_OBJECT_TYPE_URL: {{ printf "%s/api/v2/objecttypes/%s" .Values.objecttypen.baseUrlExtern .Values.objecttypen.groepUUID | quote }}
  HAAL_CENTRAAL_BASE_URL: {{ .Values.brp.baseUrl | quote }}
  INTERNE_TAAK_BASE_URL: {{ .Values.adapter.baseUrl | quote }}
  INTERNE_TAAK_OBJECT_TYPE_URL: {{ printf "%s/api/v2/objecttypes/%s" .Values.objecttypen.baseUrlIntern .Values.objecttypen.interneTaakUUID | quote }}
  KLANTEN_BASE_URL: {{ printf "%s/klanten" .Values.adapter.baseUrl | quote }}
  KVK_BASE_URL: {{ .Values.kvk.baseUrl | quote }}
  MEDEWERKER_OBJECTEN_BASE_URL: {{ .Values.adapter.baseUrl | quote }}
  MEDEWERKER_OBJECTTYPES_BASE_URL: {{ .Values.objecttypen.baseUrlExtern | quote }}
  OIDC_AUTHORITY: {{ .Values.oidc.authority | quote }}
  OIDC_MEDEWERKER_IDENTIFICATIE_CLAIM: "preferred_username"
  ORGANISATIE_IDS: {{ .Values.organisatieIds | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_HOST: {{ .Values.database.host | quote }}
  SDG_OBJECT_BASE_URL: {{ .Values.objecten.baseUrl | quote }}
  SDG_OBJECT_TYPE_URL: {{ printf "%s/api/v2/objecttypes/%s" .Values.objecttypen.baseUrlIntern .Values.objecttypen.kennisartikelUUID | quote }}
  ZAAKSYSTEEM_DEEPLINK_PROPERTY: "identificatie"
  ZAAKSYSTEEM_DEEPLINK_URL: {{ printf "%/mp/zaak/" .Values.esuite.baseUrl | quote }}
  ZAKEN_BASE_URL: {{ .Values.adapter.baseUrl | quote }}