apiVersion: v1
kind: Service
metadata:
  name: {{ default (printf "%s-frontend" (include "kiss.fullname" .)) .Values.frontend.service.name }}
  labels:
    {{- include "kiss.labelsFrontend" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kiss.selectorLabelsFrontend" . | nindent 4 }}
