apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kiss.fullname" . }}-frontend
  labels:
    {{- include "kiss.labelsFrontend" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kiss.selectorLabelsFrontend" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frontend-config.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/frontend-secret.yaml") . | sha256sum }}
      labels:
        {{- include "kiss.labelsFrontend" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kiss.serviceAccountName" . }}
      volumes:
        - name: kvk-certs-volume
          secret:
            secretName: kvk-certs
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: frontend-config
            - secretRef:
                name: frontend-secret
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.frontend.aspNetCoreEnvironment | quote }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
