apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  labels:
    {{- include "kiss.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "kiss.name" . }}-frontend-secret
stringData:
  GROEPEN_TOKEN: {{ .Values.objecten.token | quote }}
  AFDELINGEN_TOKEN: {{ .Values.objecten.token | quote }}
  REGISTERS__0__CONTACTMOMENTEN_API_CLIENT_ID: {{ .Values.adapter.clientId | quote }}
  REGISTERS__0__CONTACTMOMENTEN_API_KEY: {{ .Values.adapter.secret | quote }}
  ELASTIC_PASSWORD: {{ .Values.elastic.password | quote }}
  ELASTIC_USERNAME: {{ .Values.elastic.username | quote }}
  {{- if .Values.email.username }}
  EMAIL_USERNAME: {{ .Values.email.username | quote }}
  {{- end }}
  {{- if .Values.email.password }}
  EMAIL_PASSWORD: {{ .Values.email.password | quote }}
  {{- end }}
  ENTERPRISE_SEARCH_PRIVATE_API_KEY: {{ .Values.enterpriseSearch.privateApikey | quote }}
  ENTERPRISE_SEARCH_PUBLIC_API_KEY: {{ .Values.enterpriseSearch.publicApikey | quote }}
  HAAL_CENTRAAL_API_KEY: {{ .Values.brp.apiKey | quote }}
  REGISTERS__0__INTERNE_TAAK_CLIENT_ID: {{ .Values.adapter.clientId | quote }}
  REGISTERS__0__INTERNE_TAAK_CLIENT_SECRET: {{ .Values.adapter.secret | quote }}
  REGISTERS__0__KLANTEN_CLIENT_ID: {{ .Values.adapter.clientId | quote }}
  REGISTERS__0__KLANTEN_CLIENT_SECRET: {{ .Values.adapter.secret | quote }}
  KVK_API_KEY: {{ .Values.kvk.apikey | quote }}
  MEDEWERKER_OBJECTEN_CLIENT_ID: {{ .Values.adapter.clientId | quote }}
  MEDEWERKER_OBJECTEN_CLIENT_SECRET: {{ .Values.adapter.secret | quote }}
  MEDEWERKER_OBJECTTYPES_TOKEN: {{ .Values.objecttypen.token | quote }}
  OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.secret | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  SDG_API_KEY: {{ .Values.objecten.token | quote }}
  REGISTERS__0__ZAAKSYSTEEM_API_CLIENT_ID: {{ .Values.adapter.clientId | quote }}
  REGISTERS__0__ZAAKSYSTEEM_API_KEY: {{ .Values.adapter.secret | quote }}