apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    {{- include "kiss.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "kiss.name" . }}-frontend-config
data:
  AFDELINGEN_BASE_URL: {{ default (printf "http://objecten.%s.svc.cluster.local" .Release.Namespace) .Values.objecten.baseUrl | quote }}
  AFDELINGEN_OBJECT_TYPE_URL: {{ printf "%s/api/v2/objecttypes/%s" .Values.objecttypen.baseUrlExtern .Values.objecttypen.afdelingUUID | quote }}
  REGISTERS__0__CONTACTMOMENTEN_BASE_URL: {{ default (printf "http://kiss-adapter.%s.svc.cluster.local" .Release.Namespace) .Values.adapter.baseUrl | quote }}
  ELASTIC_BASE_URL: {{ default (printf "https://kiss-es-http.%s.svc.cluster.local:9200" .Release.Namespace) .Values.elastic.baseUrl | quote }}
  {{- if .Values.email.host }}
  EMAIL_HOST: {{ .Values.email.host | quote }}
  {{- end }}
  {{- if .Values.email.port }}
  EMAIL_PORT:  {{ .Values.email.port }}
  {{- end }}
  ENTERPRISE_SEARCH_BASE_URL: {{ default (printf "https://kiss-ent-http.%s.svc.cluster.local:3002" .Release.Namespace) .Values.enterpriseSearch.baseUrl | quote }}
  {{- if .Values.email.enableSSL }}
  EMAIL_ENABLE_SSL: {{ .Values.email.enableSSL }}
  {{- end }}
  {{- if .Values.email.feedbackFrom }}
  FEEDBACK_EMAIL_FROM: {{ .Values.email.feedbackFrom | quote }}
  {{- end }}
  {{- if .Values.email.feedbackTo }}
  FEEDBACK_EMAIL_TO:  {{ .Values.email.feedbackTo | quote }}
  {{- end }}
  GROEPEN_BASE_URL: {{ default (printf "http://objecten.%s.svc.cluster.local" .Release.Namespace) .Values.objecten.baseUrl | quote }}
  GROEPEN_OBJECT_TYPE_URL: {{ printf "%s/api/v2/objecttypes/%s" .Values.objecttypen.baseUrlExtern .Values.objecttypen.groepUUID | quote }}
  HAAL_CENTRAAL_BASE_URL: {{ .Values.brp.baseUrl | quote }}
  REGISTERS__0__INTERNE_TAAK_BASE_URL: {{ default (printf "http://kiss-adapter.%s.svc.cluster.local" .Release.Namespace) .Values.adapter.baseUrl | quote }}
  REGISTERS__0__INTERNE_TAAK_OBJECT_TYPE_URL: {{ printf "%s/api/v2/objecttypes/%s" (default (printf "http://objecttypen.%s.svc.cluster.local" .Release.Namespace) .Values.objecttypen.baseUrlIntern) .Values.objecttypen.interneTaakUUID | quote }}
  REGISTERS__0__KLANTEN_BASE_URL: {{ printf "%s/klanten" (default (printf "http://kiss-adapter.%s.svc.cluster.local" .Release.Namespace) .Values.adapter.baseUrl) | quote }}
  KVK_BASE_URL: {{ .Values.kvk.baseUrl | quote }}
  MEDEWERKER_OBJECTEN_BASE_URL:  {{ default (printf "http://kiss-adapter.%s.svc.cluster.local" .Release.Namespace) .Values.adapter.baseUrl | quote }}
  MEDEWERKER_OBJECTTYPES_BASE_URL: {{ .Values.objecttypen.baseUrlExtern | quote }}
  OIDC_AUTHORITY: {{ .Values.oidc.authority | quote }}
  OIDC_MEDEWERKER_IDENTIFICATIE_CLAIM: {{ .Values.oidc.medewerkerIdentificatieClaim | quote }}
  {{- if .Values.oidc.medewerkerIdentificatieTruncate }}
  OIDC_MEDEWERKER_IDENTIFICATIE_TRUNCATE: {{ .Values.oidc.medewerkerIdentificatieTruncate }}
  {{- end }}
  ORGANISATIE_IDS: {{ .Values.organisatieIds | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_HOST: {{ .Values.database.host | quote }}
  SDG_OBJECT_BASE_URL: {{ default (printf "http://objecten.%s.svc.cluster.local" .Release.Namespace) .Values.objecten.baseUrl | quote }}
  SDG_OBJECT_TYPE_URL: {{ printf "%s/api/v2/objecttypes/%s" (default (printf "http://objecttypen.%s.svc.cluster.local" .Release.Namespace) .Values.objecttypen.baseUrlIntern) .Values.objecttypen.kennisartikelUUID | quote }}
  REGISTERS__0__ZAAKSYSTEEM_DEEPLINK_PROPERTY: "identificatie"
  REGISTERS__0__ZAAKSYSTEEM_DEEPLINK_URL: {{ printf "%s/mp/zaak/" .Values.esuite.baseUrl | quote }}
  REGISTERS__0__ZAAKSYSTEEM_BASE_URL:  {{ default (printf "http://kiss-adapter.%s.svc.cluster.local" .Release.Namespace) .Values.adapter.baseUrl | quote }}
  REGISTERS__0__IS_DEFAULT: {{ .Values.esuite.isDefault | quote }}
  REGISTERS__0__REGISTRY_VERSION: "OpenKlant1"
