apiVersion: v1
kind: Secret
metadata:
  name: kiss-sync-secret
  labels:
    {{- include "kiss.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "kiss.name" . }}-sync-secret
stringData:
  ELASTIC_PASSWORD: {{ .Values.elastic.password | quote }}
  ELASTIC_USERNAME: {{ .Values.elastic.username | quote }}
  ENTERPRISE_SEARCH_PRIVATE_API_KEY: {{ .Values.enterpriseSearch.privateApikey | quote }}
  MEDEWERKER_OBJECTEN_CLIENT_ID: {{ .Values.adapter.clientId | quote }}
  MEDEWERKER_OBJECTEN_CLIENT_SECRET: {{ .Values.adapter.secret | quote }}
  SDG_OBJECTEN_TOKEN: {{ .Values.objecten.token | quote }}
  VAC_OBJECTEN_TOKEN: {{ .Values.objecten.token | quote }}
