apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana.dashboardsConfigMaps.logs }}
  labels:
    grafana_dashboard: "1"
data:
  logging-logs.json: |-
{{ .Files.Get "dashboards/logging-logs.json" | indent 4 }}
