apiVersion: v1
kind: Service
metadata:
  name: brpmock
  labels:
    app.kubernetes.io/name: brpmock
    {{- include "bm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "bm.name" . }}-brpproxy
  ports:
    - name: http
      port: 80
      targetPort: http
