apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bm.name" . }}-gbamock
  labels:
    app.kubernetes.io/name: {{ include "bm.name" . }}-gbamock
    {{- include "bm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bm.name" . }}-gbamock
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bm.name" . }}-gbamock
        {{- include "bm.labels" . | nindent 8 }}
    spec:
      containers:
        - name: gbamock
          image: "{{ .Values.gbamock.image.repository }}:{{ .Values.gbamock.image.tag }}"
          imagePullPolicy: {{ .Values.gbamock.image.pullPolicy }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Release
            - name: ASPNETCORE_URLS
              value: http://+:5010
          ports:
            - name: http
              containerPort: 5010
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
