apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "podiumd.fullname" . }}-kanalen-config
  labels:
    {{- include "podiumd.labels" . | nindent 4 }}
    app.kubernetes.io/component: openzaak
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      labels:
        {{- include "podiumd.labels" . | nindent 8 }}
        app.kubernetes.io/component: openzaak
    spec:
      serviceAccountName: {{ template "podiumd.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: {{ include "podiumd.fullname" . }}-kanalen-config
          image: "{{ .Values.openzaak.image.repository }}:{{ .Values.openzaak.image.tag }}"
          imagePullPolicy: {{ .Values.openzaak.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: podiumd-open-zaak
            - configMapRef:
                name: podiumd-open-zaak
{{/*            - secretRef:*/}}
{{/*                name: {{ .Values.openzaak.existingSecret | default (include "openzaak.fullname" .) }}*/}}
{{/*            - configMapRef:*/}}
{{/*                name: {{ include "openzaak.fullname" . }}*/}}
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              /app/src/manage.py register_kanalen
          volumeMounts:
            - name: media
              mountPath: /app/private-media
              subPath: {{ .Values.openzaak.persistence.privateMediaMountSubpath | default "openzaak/private_media" }}
            - name: media
              mountPath: /app/media
              subPath: {{ .Values.openzaak.persistence.mediaMountSubpath  | default "openzaak/media" }}
      volumes:
        - name: media
          persistentVolumeClaim:
          {{- if .Values.openzaak.persistence.enabled }}
            claimName: {{ .Values.openzaak.persistence.existingClaim }}
          {{- else }}
          emptyDir: { }
          {{- end }}
