{{- if .Values.kiss.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podiumd.fullname" . }}-frontend
  labels:
    {{- include "podiumd.labelsFrontend" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "podiumd.selectorLabelsFrontend" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frontend-config.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/frontend-secret.yaml") . | sha256sum }}
      labels:
        {{- include "podiumd.labelsFrontend" . | nindent 8 }}
    spec:
      {{- with .Values.kiss.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "podiumd.serviceAccountName" . }}
      volumes:
        - name: kvk-certs-volume
          secret:
            secretName: kvk-certs
      containers:
        - name: frontend
          image: "{{ .Values.kiss.frontend.image.repository }}:{{ .Values.kiss.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.kiss.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.kiss.frontend.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: frontend-config
            - secretRef:
                name: frontend-secret
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.kiss.frontend.aspNetCoreEnvironment | quote }}
          {{- if .Values.kiss.frontend.extraVolumeMounts }}
          volumeMounts:
            {{- include "kiss-frontend.tplvalues.render" ( dict "value" .Values.kiss.frontend.extraVolumeMounts "context" $ ) | nindent 12 }}
          {{- end }}
          {{- if .Values.kiss.frontend.extraVolumes }}
          volumes:
            {{- include "kiss-frontend.tplvalues.render" ( dict "value" .Values.kiss.frontend.extraVolumes "context" $ ) | nindent 8 }}
          {{- end }}

      {{- with .Values.kiss.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}