{{- if .Values.kiss.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  labels:
    {{- include "podiumd.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "podiumd.name" . }}-frontend-secret
stringData:
  GROEPEN_TOKEN: {{ .Values.kiss.objecten.token | quote }}
  AFDELINGEN_TOKEN: {{ .Values.kiss.objecten.token | quote }}
  REGISTERS__0__CONTACTMOMENTEN_API_CLIENT_ID: {{ .Values.kiss.adapter.clientId | quote }}
  REGISTERS__0__CONTACTMOMENTEN_API_KEY: {{ .Values.kiss.adapter.secret | quote }}
  ELASTIC_PASSWORD: {{ .Values.kiss.elastic.password | quote }}
  ELASTIC_USERNAME: {{ .Values.kiss.elastic.username | quote }}
  {{- if .Values.kiss.email.username }}
  EMAIL_USERNAME: {{ .Values.kiss.email.username | quote }}
  {{- end }}
  {{- if .Values.kiss.email.password }}
  EMAIL_PASSWORD: {{ .Values.kiss.email.password | quote }}
  {{- end }}
  ENTERPRISE_SEARCH_PRIVATE_API_KEY: {{ .Values.kiss.enterpriseSearch.privateApikey | quote }}
  ENTERPRISE_SEARCH_PUBLIC_API_KEY: {{ .Values.kiss.enterpriseSearch.publicApikey | quote }}
  HAAL_CENTRAAL_API_KEY: {{ .Values.kiss.brp.apiKey | quote }}
  REGISTERS__0__INTERNE_TAAK_CLIENT_ID: {{ .Values.kiss.adapter.clientId | quote }}
  REGISTERS__0__INTERNE_TAAK_CLIENT_SECRET: {{ .Values.kiss.adapter.secret | quote }}
  REGISTERS__0__KLANTEN_CLIENT_ID: {{ .Values.kiss.adapter.clientId | quote }}
  REGISTERS__0__KLANTEN_CLIENT_SECRET: {{ .Values.kiss.adapter.secret | quote }}
  KVK_API_KEY: {{ .Values.kiss.kvk.apikey | quote }}
  MEDEWERKER_OBJECTEN_CLIENT_ID: {{ .Values.kiss.adapter.clientId | quote }}
  MEDEWERKER_OBJECTEN_CLIENT_SECRET: {{ .Values.kiss.adapter.secret | quote }}
  MEDEWERKER_OBJECTTYPES_TOKEN: {{ .Values.kiss.objecttypen.token | quote }}
  MANAGEMENTINFORMATIE_API_KEY: {{ .Values.kiss.managementApiKey | quote }}
  OIDC_CLIENT_ID: {{ .Values.kiss.oidc.clientId | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.kiss.oidc.secret | quote }}
  POSTGRES_PASSWORD: {{ .Values.kiss.database.password | quote }}
  POSTGRES_USER: {{ .Values.kiss.database.user | quote }}
  SDG_API_KEY: {{ .Values.kiss.objecten.token | quote }}
  VAC_OBJECTEN_TOKEN: {{ .Values.kiss.vac.objectenToken | quote }}
  REGISTERS__0__ZAAKSYSTEEM_API_CLIENT_ID: {{ .Values.kiss.adapter.clientId | quote }}
  REGISTERS__0__ZAAKSYSTEEM_API_KEY: {{ .Values.kiss.adapter.secret | quote }}

{{- end }}