{{- if and .Values.global.configuration.enabled .Values.opennotificaties.configuration.enabled .Values.opennotificaties.configuration.http_request_job.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: http-request-files-configmap
  labels:
    {{- include "podiumd.labels" . | nindent 4 }}
data:
  {{ .Files.AsConfig | nindent 4 }}
{{- end }}