apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "podiumd.fullname" . }}-http-request-files-configmap
  labels:
    {{- include "podiumd.labels" . | nindent 4 }}
data:
  {{ .Files.AsConfig | nindent 4 }}
