apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "podiumd.fullname" . }}-kanalen-create
  labels:
    {{- include "podiumd.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        {{- include "podiumd.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "podiumd.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: intellij-http-client
          image: jetbrains/intellij-http-client
          args:
            - --env-file
            - /shared/http-client.private.env.json
            - --env
            - tmp
            - /config/kanalen.http
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
            - name: config-volume
              mountPath: /config/kanalen.http
              subPath: kanalen.http
      initContainers:
        - name: jwt-cli
          image: bitnami/jwt-cli
          args:
            - encode
            - --iss
            - {{ .Values.global.configuration.openzaakNotificatiesClientId }}
            - --secret
            - {{ .Values.global.configuration.openzaakNotificatiesSecret }}
            - --payload
            - client_id={{ .Values.global.configuration.openzaakNotificatiesClientId }}
            - --out
            - /shared/jwt
          volumeMounts:
            - mountPath: /shared
              name: shared-volume
        - name: wait-and-create-http-client-env
          image: alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Wait for 120 seconds ..." && \
              sleep 120 && \
              apk add --no-cache jq > /dev/null && \
              JWT_CONTENT=$(cat /shared/jwt) && \
              echo $(jq -n --arg jwt "$JWT_CONTENT" '{"tmp": {"jwt": $jwt}}') > /shared/http-client.private.env.json
          volumeMounts:
            - mountPath: /shared
              name: shared-volume
      volumes:
        - name: shared-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: kanalen-create-config

