apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.keycloak.keycloakConfigCli.existingConfigmap }}
  labels:
    {{- include "podiumd.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak-config-cli
data:
  realm.yaml: |
      enabled: true
      realm: podiumd
      displayName: {{ required ".Values.keycloak.config.realmDisplayName is missing" .Values.keycloak.config.realmDisplayName | quote }}
      loginWithEmailAllowed: true
      rememberMe: true
      attributes:
        frontendUrl: {{ required ".Values.keycloak.config.realmFrontendUrl is missing" .Values.keycloak.config.realmFrontendUrl | quote }}
      clients:
        - clientId: openzaak
          name: Open Zaak
          enabled: true
          clientAuthenticatorType: client-secret
          redirectUris:
            - "{{ required ".Values.global.configuration.openzaakUrlExtern is missing" .Values.global.configuration.openzaakUrlExtern }}/*"
          webOrigins:
            - "{{ .Values.global.configuration.openzaakUrlExtern }}/*"
          secret: {{ required ".Values.global.configuration.openzaakOidcSecret is missing" .Values.global.configuration.openzaakOidcSecret | quote }}
        - clientId: opennotificaties
          name: Open Notificaties
          enabled: true
          clientAuthenticatorType: client-secret
          redirectUris:
            - "{{ required ".Values.global.configuration.opennotificatiesUrlExtern is missing" .Values.global.configuration.opennotificatiesUrlExtern }}/*"
          webOrigins:
            - "{{ .Values.global.configuration.opennotificatiesUrlExtern }}/*"
          secret: {{ required ".Values.global.configuration.opennotificatiesOidcSecret is missing" .Values.global.configuration.opennotificatiesOidcSecret | quote }}
        - clientId: objecten
          name: Objecten
          enabled: true
          clientAuthenticatorType: client-secret
          redirectUris:
            - "{{ required ".Values.global.configuration.objectenUrlExtern is missing" .Values.global.configuration.objectenUrlExtern }}/*"
          webOrigins:
            - "{{ .Values.global.configuration.objectenUrlExtern }}/*"
          secret: {{ required ".Values.global.configuration.objectenOidcSecret is missing" .Values.global.configuration.objectenOidcSecret | quote }}
        - clientId: objecttypen
          name: Objecttypen
          enabled: true
          clientAuthenticatorType: client-secret
          redirectUris:
            - "{{ required ".Values.global.configuration.objecttypenUrlExtern is missing" .Values.global.configuration.objecttypenUrlExtern }}/*"
          webOrigins:
            - "{{ .Values.global.configuration.objecttypenUrlExtern }}/*"
          secret: {{ required ".Values.global.configuration.objecttypenOidcSecret is missing" .Values.global.configuration.objecttypenOidcSecret | quote }}
        - clientId: openforms
          name: Open Forms
          enabled: true
          clientAuthenticatorType: client-secret
          redirectUris:
            - "{{ required ".Values.global.configuration.openformsUrlExtern is missing" .Values.global.configuration.openformsUrlExtern }}/*"
          webOrigins:
            - "{{ .Values.global.configuration.openformsUrlExtern }}/*"
          secret: {{ required ".Values.global.configuration.openformsOidcSecret is missing" .Values.global.configuration.openformsOidcSecret | quote }}
        - clientId: openklant
          name: Open Klant
          enabled: true
          clientAuthenticatorType: client-secret
          redirectUris:
            - "{{ required ".Values.global.configuration.openklantUrlExtern is missing" .Values.global.configuration.openklantUrlExtern }}/*"
          webOrigins:
            - "{{ .Values.global.configuration.openklantUrlExtern }}/*"
          secret: {{ required ".Values.global.configuration.openklantOidcSecret is missing" .Values.global.configuration.openklantOidcSecret | quote }}
        - clientId: openinwoner
          name: Open Inwoner
          enabled: true
          clientAuthenticatorType: client-secret
          redirectUris:
            - "{{ required ".Values.global.configuration.openinwonerUrlExtern is missing" .Values.global.configuration.openinwonerUrlExtern }}/*"
          webOrigins:
            - "{{ .Values.global.configuration.openinwonerUrlExtern }}/*"
          secret: {{ required ".Values.global.configuration.openinwonerOidcSecret is missing" .Values.global.configuration.openinwonerOidcSecret | quote }}
        - clientId: kiss
          name: Kiss
          enabled: true
          clientAuthenticatorType: client-secret
          redirectUris:
            - "{{ required ".Values.global.configuration.kissUrlExtern is missing" .Values.global.configuration.kissUrlExtern }}/*"
          webOrigins:
            - "{{ .Values.global.configuration.kissUrlExtern }}/*"
          secret: {{ required ".Values.global.configuration.kissOidcSecret is missing" .Values.global.configuration.kissOidcSecret | quote }}
          protocolMappers:
            - name: kiss-roles
              protocol: openid-connect
              protocolMapper: oidc-usermodel-client-role-mapper
              config:
                usermodel.clientRoleMapping.clientId: kiss
                multivalued: true
                claim.name: roles
                id.token.claim: true
                access.token.claim: true
                lightweight.claim: true
                userinfo.token.claim: true
                introspection.token.claim: true
        - clientId: zac
          name: Zaakafhandelcomponent
          enabled: true
          clientAuthenticatorType: client-secret
          redirectUris:
            - "{{ required ".Values.global.configuration.zacUrlExtern is missing" .Values.global.configuration.zacUrlExtern }}/*"
          webOrigins:
            - "{{ .Values.global.configuration.zacUrlExtern }}/*"
          secret: {{ required ".Values.global.configuration.zacOidcSecret is missing" .Values.global.configuration.zacOidcSecret | quote }}
          protocolMappers:
            - name: zac-roles
              protocol: openid-connect
              protocolMapper: oidc-usermodel-client-role-mapper
              config:
                usermodel.clientRoleMapping.clientId: zac
                multivalued: true
                claim.name: roles
                id.token.claim: true
                access.token.claim: true
                lightweight.claim: true
                userinfo.token.claim: true
                introspection.token.claim: true
      roles:
        realm:
          - name: podiumd-admin
            description: PodiumD Administrator
        client:
          kiss:
            - name: Redacteur
            - name: Klantcontactmedewerker
          zac:
            - name: zaakafhandelcomponent_user
            - name: behandelaar
            - name: beheerder
            - name: coordinator
            - name: recordmanager
            - name: domein_elk_zaaktype
      components:
        org.keycloak.storage.UserStorageProvider:
          - name: OpenLDAP
            providerId: ldap
            config:
              vendor:
                - other
              connectionUrl:
                - ldap://openldap.openldap:1389
              connectionPooling:
                - true
              bindDn:
                - cn=admin,dc=dimpact-lab,dc=org
              bindCredential:
                - admin
              editMode:
                - WRITABLE
              usersDn:
                - ou=lab3,dc=dimpact-lab,dc=org
              usernameLDAPAttribute:
                - cn
              rdnLDAPAttribute:
                - cn
              uuidLDAPAttribute:
                - entryUUID
              userObjectClasses:
                - inetOrgPerson
              pagination:
                - true
              importEnabled:
                - false
              batchSizeForSync:
                - "1000"
              fullSyncPeriod:
                - "-1"
              changedSyncPeriod:
                - "-1"
            subComponents:
              org.keycloak.storage.ldap.mappers.LDAPStorageMapper:
                - name: groups
                  providerId: group-ldap-mapper
                  config:
                    groups.dn:
                      - ou=lab3,dc=dimpact-lab,dc=org
                    group.name.ldap.attribute:
                      - cn
                    group.object.classes:
                      - groupOfUniqueNames,extensibleObject
                    preserve.group.inheritance:
                      - false
                    ignore.missing.groups:
                      - false
                    membership.ldap.attribute:
                      - uniqueMember
                    membership.attribute.type:
                      - DN
                    membership.user.ldap.attribute:
                      - cn
                    mode:
                      - LDAP_ONLY
                    user.roles.retrieve.strategy:
                      - LOAD_GROUPS_BY_MEMBER_ATTRIBUTE
                    memberof.ldap.attribute:
                      - memberOf
                    mapped.group.attributes:
                      - description,email
                    drop.non.existing.groups.during.sync:
                      - true
                    groups.path:
                      - "/"
