{{- if and (index .Values "keycloak-operator").enabled (index .Values "keycloak-operator").jobs.ensureOperatorSa.enabled }}
{{- $clientSecret := (index .Values "keycloak-operator").jobs.ensureOperatorSa.clientSecret }}
{{- if $clientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-operator-client-secret
  labels:
    {{- include "podiumd.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
type: Opaque
stringData:
  clientId: "keycloak-operator"
  client-secret: {{ $clientSecret | quote }}
{{- end }}
{{- end }}
