{{- if .Values.kiss.enabled -}}
{{- if .Values.kiss.sync.domain.enabled | default true }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: podiumd-sync-domain-cron-job
  labels:
    {{- include "podiumd.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "podiumd.name" . }}-sync-domain-cron-job
spec:
  schedule: {{ .Values.kiss.sync.domain.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.kiss.sync.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.kiss.sync.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "podiumd.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "podiumd.name" . }}-sync-domain-cron-job
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: sync-domain
              image: "{{ .Values.kiss.sync.image.repository }}:{{ .Values.kiss.sync.image.tag }}"
              imagePullPolicy: {{ .Values.kiss.sync.image.pullPolicy }}
              args:
                - domain
                - {{ .Values.kiss.sync.domain.url | quote }}
              envFrom:
                - configMapRef:
                    name: podiumd-sync-config
                - secretRef:
                    name: podiumd-sync-secret
          {{- with .Values.kiss.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
{{- end }}