{{- if .Values.zaakbrug.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: zaakbrug-secrets
  labels:
    {{- include "podiumd.labels" . | nindent 4 }}
    app.kubernetes.io/component: zaakbrug
type: Opaque
stringData:
  credentials.properties: |
    zaken-api.jwt/username={{ .Values.zaakbrug.frank.zakenApi.jwt.username | default "zaakbrug" }}
    zaken-api.jwt/password={{ required "zaakbrug.frank.zakenApi.jwt.password is required when zaakbrug.enabled=true" .Values.zaakbrug.frank.zakenApi.jwt.password }}
{{- end }}
