tags:
  contact: true
  zaak: false

global:
  configuration:
    enabled: true
    overwrite: true
    organization: Example gemeente
    openzaakAutorisatiesApi: http//openzaak.podiumd.svc.cluster.local/autorisaties/api/v1/
    notificatiesApi: http://opennotificaties.podiumd.svc.cluster.local/api/v1/
    notificatiesOpenzaakClientId: notificaties
    notificatiesOpenzaakSecret: notificaties-secret
    openzaakNotificatiesClientId: openzaak
    openzaakNotificatiesSecret: openzaak-secret

  settings:
    databaseHost: ""

  imageRegistry: ""

persistentVolume:
  volumeAttributeShareName: ""
  volumeAttributeResourceGroup: ""
  nodeStageSecretRefName: ""
  nodeStageSecretRefNamespace: ""

keycloak:
  config:
    realmDisplayName: PodiumD
    realmFrontendUrl: https://keycloak.example.nl
    adminFrontendUrl: https://keycloak-admin.example.nl
  auth:
    adminUser: admin
    adminPassword: ChangeMeNow
  externalDatabase:
    host: "dummy"
    database: ""
    user: ""
  keycloakConfigCli:
    enabled: true
    existingConfigmap: keycloak-config
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
  production: true
  proxy: edge
  postgresql:
    enabled: false
  nameOverride: keycloak
  fullnameOverride: keycloak
  extraEnvVarsCM: keycloak-extra-env-vars

openldap:
  persistence:
    size: 1Gi
    existingClaim: openldap
  persistentVolume:
    volumeAttributeShareName: openldap
  nameOverride: openldap
  fullnameOverride: openldap

brpmock:
  enabled: false
  nameOverride: brpmock

openzaak:
  configuration:
    oidcUrl: https://openzaak.example.nl
    oidcSecret: "<openzaak>"
    initContainer:
      enabled: true
    job:
      enabled: false
  settings:
    allowedHosts: openzaak-nginx.podiumd.svc.cluster.local
    email:
      port: 587
      useTLS: true
    disable2fa: true
  persistence:
    size: 10Gi
    existingClaim: openzaak
  persistentVolume:
    volumeAttributeShareName: openzaak
  image:
    tag: "1.15.0"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  worker:
    replicaCount: 1
    resources:
      requests:
        cpu: 10m
        memory: 480Mi
  nameOverride: openzaak
  fullnameOverride: openzaak
  flower:
    enabled: false
  beat:
    resources:
      requests:
        cpu: 10m
        memory: 160Mi    
  nginx:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
  redis:
    nameOverride: openzaak-redis
    fullnameOverride: openzaak-redis
    master:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: ""
      resources:
        requests:
          cpu: 10m
          memory: 64Mi        

opennotificaties:
  configuration:
    enabled: true
    overwrite: true
    oidcUrl: https://opennotificaties.example.nl
    oidcSecret: "<opennotificaties>"
  settings:
    allowedHosts: opennotificaties.podiumd.svc.cluster.local
    maxRetries: 5
    retryBackoff: 3
    retryBackoffMax: 48
    email:
      port: 587
      useTLS: true
    disable2fa: true
  persistence:
    size: 10Gi
    existingClaim: opennotificaties
  persistentVolume:
    volumeAttributeShareName: opennotificaties
  image:
    tag: "1.7.1"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  worker:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 386Mi
  nameOverride: opennotificaties
  fullnameOverride: opennotificaties
  flower:
    enabled: false
  rabbitmq:
    resources:
      requests:
        cpu: 300m
        memory: 256Mi
    nameOverride: opennotificaties-rabbitmq
    fullnameOverride: opennotificaties-rabbitmq
    auth:
      username: guest
      password: guest
      erlangCookie: SUPER-SECRET
  redis:
    nameOverride: opennotificaties-redis
    fullnameOverride: opennotificaties-redis
    master:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: ""
      resources:
        requests:
          cpu: 10m
          memory: 64Mi        

objecten:
  configuration:
    oidcUrl: https://objecten.example.nl
    oidcSecret: "<objecten>"
  settings:
    allowedHosts: objecten.podiumd.svc.cluster.local
    email:
      port: 587
      useTLS: true
    disable2fa: true
  persistence:
    size: 10Gi
    existingClaim: objecten
  persistentVolume:
    volumeAttributeShareName: objecten
  image:
    tag: "2.4.4"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  worker:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 192Mi
  nameOverride: objecten
  fullnameOverride: objecten
  flower:
    enabled: false
  redis:
    nameOverride: objecten-redis
    fullnameOverride: objecten-redis
    master:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: ""
      resources:
        requests:
          cpu: 10m
          memory: 64Mi        

objecttypen:
  configuration:
    oidcUrl: https://objecttypen.example.nl
    oidcSecret: "<objecttypen>"
  settings:
    allowedHosts: objecttypen.podiumd.svc.cluster.local
    email:
      port: 587
      useTLS: true
    disable2fa: true
  image:
    tag: "2.2.2"
  resources:
    requests:
      cpu: 10m
      memory: 160Mi
  nameOverride: objecttypen
  fullnameOverride: objecttypen
  redis:
    nameOverride: objecttypen-redis
    fullnameOverride: objecttypen-redis
    master:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: ""    
      resources:
        requests:
          cpu: 10m
          memory: 64Mi

openklant:
  configuration:
    oidcUrl: https://openklant.example.nl
    oidcSecret: "<openklant>"
  settings:
    allowedHosts: openklant.podiumd.svc.cluster.local
    email:
      port: 587
      useTLS: true
    disable2fa: true
  image:
    tag: "2.3.0"
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
  worker:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
  nameOverride: openklant
  fullnameOverride: openklant
  redis:
    nameOverride: openklant-redis
    fullnameOverride: openklant-redis
    master:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: ""
      resources:
        requests:
          cpu: 10m
          memory: 64Mi        
        
openformulieren:
  configuration:
    oidcUrl: https://openformulieren.example.nl
    oidcSecret: "<openformulieren>"
  settings:
    allowedHosts: openformulieren-nginx.podiumd.svc.cluster.local
    email:
      port: 587
      useTLS: true
  persistence:
    size: 10Gi
    existingClaim: openformulieren
    mediaMountSubpath: openformulieren/media
    privateMediaMountSubpath: openformulieren/private_media
  persistentVolume:
    volumeAttributeShareName: openformulieren
  image:
    tag: "2.7.9"
  resources:
    requests:
      cpu: 100m
      memory: 650Mi
  worker:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
  nameOverride: openformulieren
  fullnameOverride: openformulieren
  flower:
    enabled: false
  beat:
    resources:
      requests:
        cpu: 10m
        memory: 160Mi
  nginx:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
    config:
      clientMaxBodySize: 100M
  redis:
    nameOverride: openformulieren-redis
    fullnameOverride: openformulieren-redis
    master:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: ""
      resources:
        requests:
          cpu: 10m
          memory: 64Mi

openinwoner:
  configuration:
    oidcUrl: https://openinwoner.example.nl
    oidcSecret: "<openinwoner>"
  settings:
    allowedHosts: openinwoner-nginx.podiumd.svc.cluster.local
    brpVersion: ""
    digidMock: ""
    eherkenningMock: ""    
    email:
      port: 587
      useTLS: true
  persistence:
    size: 10Gi
    existingClaim: openinwoner
  persistentVolume:
    volumeAttributeShareName: openinwoner
  image:
    tag: "1.21.3"
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
  worker:
    replicaCount: 1
    resources:
      requests:
        cpu: 200m
        memory: 640Mi
  nameOverride: openinwoner
  fullnameOverride: openinwoner
  nginx:
    config:
      basicAuth:
        # Enable this when digid mock is set to digidMock: "true"
        enabled: false
        # You need to generate the encrypted basic auth password yourself with htpasswd or openssl.
        # This is an example user
        users: |-
          dimpact:$apr1$E03dZmYK$npjTaXfI05tMJ63gB8dxm. 
      clientMaxBodySize: 100M
    resources:
      requests:
        cpu: 30m
        memory: 8Mi
  redis:
    nameOverride: openinwoner-redis
    fullnameOverride: openinwoner-redis
    master:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: ""    
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
  elasticsearch:
    nameOverride: openinwoner-elasticsearch
    fullnameOverride: openinwoner-elasticsearch
    master:
      resources:
        requests:
          cpu: 100m
          memory: 640Mi
    data:
      resources:
        requests:
          cpu: 100m
    coordinating:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi

kisselastic:
  kibanaDomain: kiss-kb-http.podiumd.svc.cluster.local:5601
  eck-operator:
    managedNamespaces:
      - podiumd

kiss:
  enabled: true
  configuration:
    oidcUrl: https://kiss.example.nl
    oidcSecret: "<kiss>"

  brp:
    baseUrl: ""
    apiKey: ""

  elastic:
    baseUrl: ""
    username: elastic
    password: ""

  enterpriseSearch:
    baseUrl: ""
    privateApikey: ""
    publicApikey: ""
    engine: kiss-engine

  esuite:
    baseUrl: ""
    clientId: kiss
    secret: ""
    contactverzoektypen: []

  database:
    host: ""
    name: ""
    user: ""
    password: ""

  email:
    host: ""
    port: null
    username: ""
    password: ""
    enableSSL: null
    feedbackFrom: ""
    feedbackTo: ""

  kvk:
    baseUrl: ""
    apikey: ""

  objecten:
    baseUrl: ""
    token: ""

  objecttypen:
    baseUrlIntern: ""
    baseUrlExtern: ""
    token: ""
    afdelingUUID: ""
    groepUUID: ""
    interneTaakUUID: ""
    kennisartikelUUID: ""
    medewerkerUUID: ""
    vacUUID: ""

  oidc:
    authority: ""
    clientId: kiss
    secret: ""
    medewerkerIdentificatieClaim: preferred_username
    medewerkerIdentificatieTruncate: null

  organisatieIds: ""

  imagePullSecrets: []



  nodeSelector: {}

  frontend:
    service:
      name: ""
    image:
      repository: ghcr.io/klantinteractie-servicesysteem/kiss-frontend
      tag: "v0.5.0"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
    aspNetCoreEnvironment: Production

  adapter:
    baseUrl: ""
    clientId: kiss_intern
    secret: ""
    image:
      repository: ghcr.io/icatt-menselijk-digitaal/podiumd-adapter
      tag: "latest"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 10m
        memory: 100Mi

  sync:
    initialSync: true
    schedule:
      kennisbank: "*/59 * * * *"
      smoelenboek: "*/59 * * * *"
      vac: "*/59 * * * *"
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    image:
      repository: "ghcr.io/klantinteractie-servicesysteem/kiss-elastic-sync"
      tag: "latest"
      pullPolicy: IfNotPresent

  alpine:
     image:
       repository: "alpine"
       tag: "3.20"
       pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

zac:
  configuration:
    oidcUrl: https://zac.example.nl
    oidcSecret: "<zac>"
  nameOverride: zac
  fullnameOverride: zac

clamav:
  image:
    tag: "1.4.1"
  nameOverride: clamav
  fullnameOverride: clamav
  clamdConfig: |
    ###############
    # General
    ###############

    DatabaseDirectory /var/lib/clamav
    TemporaryDirectory /tmp
    LogTime yes
    # CUSTOM: Use pid file in tmp
    PidFile /tmp/clamd.pid
    LocalSocket /tmp/clamd.sock
    TCPSocket 3310
    Foreground yes

    ###############
    # Results
    ###############

    DetectPUA yes
    ExcludePUA NetTool
    ExcludePUA PWTool
    HeuristicAlerts yes
    Bytecode yes

    ###############
    # Scan
    ###############

    ScanPE yes
    DisableCertCheck yes
    ScanELF yes
    AlertBrokenExecutables yes
    ScanOLE2 yes
    ScanPDF yes
    ScanSWF yes
    ScanMail yes
    PhishingSignatures yes
    PhishingScanURLs yes
    ScanHTML yes
    ScanArchive yes

    ###############
    # Scan
    ###############

    MaxScanSize 150M
    MaxFileSize 30M
    MaxRecursion 10
    MaxFiles 15000
    MaxEmbeddedPE 10M
    MaxHTMLNormalize 10M
    MaxHTMLNoTags 2M
    MaxScriptNormalize 5M
    MaxZipTypeRcg 1M
    MaxPartitions 128
    MaxIconsPE 200
    PCREMatchLimit 10000
    PCRERecMatchLimit 10000
  freshclamConfig: |
    ###############
    # General
    ###############

    DatabaseDirectory /var/lib/clamav/
    UpdateLogFile /dev/stdout
    LogTime yes
    # CUSTOM: Use pid file in tmp
    PidFile /tmp/freshclam.pid
    # CUSTOM: Set defined user
    DatabaseOwner 2000

    ###############
    # Updates
    ###############

    DatabaseMirror database.clamav.net
    ScriptedUpdates yes
    NotifyClamd /etc/clamav/clamd.conf
    Bytecode yes
  resources:
    requests:
      cpu: 1000m
      memory: 4Gi

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

httpRequestJob:
  intellijHttpClient:
    image:
      repository: jetbrains/intellij-http-client
      tag: "243.22562.13"
  jwtCli:
    image:
      repository: bitnami/jwt-cli
      tag: "6.1.1"
  alpine:
    image:
      repository: alpine
      tag: "3.20"
  nodeSelector: {}
