keycloak:
  enabled: true
  postgresql:
    enabled: false

openzaak:
  enabled: true
  configuration:
    initContainer:
      enabled: true
    cronjob:
      enabled: false
  nameOverride: open-zaak
  image:
    tag: 1.12.3
  resources:
    requests:
      cpu: 100m
      memory: 400Mi
  flower:
    enabled: false
  redis:
    nameOverride: open-zaak-redis

opennotificaties:
  enabled: true
  configuration:
    initContainer:
      enabled: true
    cronjob:
      enabled: false
  nameOverride: open-notificaties
  image:
    tag: 1.5.2
  resources:
    requests:
      cpu: 10m
      memory: 200Mi
  flower:
    enabled: false
  rabbitmq:
    nameOverride: open-notificaties-rabbitmq
    auth:
      username: guest
      password: guest
      erlangCookie: SUPER-SECRET
  redis:
    nameOverride: open-notificaties-redis

objecten:
  enabled: true
  image:
    tag: 2.3.1
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
  settings:
    disable2fa: true
  flower:
    enabled: false
  redis:
    nameOverride: objecten-redis

objecttypen:
  enabled: true
  image:
    tag: 2.1.2
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
  settings:
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false

openforms:
  enabled: true
  image:
    tag: 2.6.6
  nameOverride: open-forms
  resources:
    requests:
      cpu: 10m
      memory: 600Mi
  settings:
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false
  flower:
    enabled: false
  redis:
    nameOverride: open-forms-redis

openklant:
  enabled: true
  image:
    tag: 2.0.0
  nameOverride: open-klant
  resources:
    requests:
      cpu: 10m
      memory: 600Mi
  settings:
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false
  redis:
    nameOverride: open-klant-redis

openinwoner:
  enabled: true
  image:
    tag: 1.16.5
  nameOverride: open-inwoner
  resources:
    requests:
      cpu: 10m
      memory: 600Mi
  settings:
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false
  redis:
    nameOverride: open-inwoner-redis
  elasticsearch:
    nameOverride: open-inwoner-elasticsearch
