tags:
  portaal: false
  contact: false
  zaak: false

global:
  configuration:
    enabled: true
    organization: Example gemeente
    openzaakAutorisatiesApi: https://openzaak.example.nl/autorisaties/api/v1/
    notificatiesApi: https://opennotificaties.example.nl/api/v1/
    notificatiesOpenzaakClientId: notificaties
    notificatiesOpenzaakSecret: notificaties-secret
    openzaakNotificatiesClientId: openzaak
    openzaakNotificatiesSecret: openzaak-secret
  imageRegistry: ""

persistentVolume:
  volumeAttributeShareName: ""
  volumeAttributeResourceGroup: ""
  nodeStageSecretRefName: ""
  nodeStageSecretRefNamespace: ""

keycloak:
  config:
    realmDisplayName: PodiumD
    realmFrontendUrl: https://keycloak.example.nl
    adminFrontendUrl: https://keycloak-admin.example.nl
  auth:
    adminUser: admin
    adminPassword: ChangeMeNow
  externalDatabase:
    database: ""
    user: ""
  keycloakConfigCli:
    enabled: true
    existingConfigmap: keycloak-config
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 1024Mi
  production: true
  proxy: edge
  postgresql:
    enabled: false
  nameOverride: keycloak
  fullnameOverride: keycloak
  extraEnvVarsCM: keycloak-extra-env-vars

openldap:
  persistence:
    size: 1Gi
    existingClaim: openldap
  persistentVolume:
    volumeAttributeShareName: openldap
  nameOverride: openldap
  fullnameOverride: openldap

brpmock:
  enabled: false
  nameOverride: brpmock

openzaak:
  configuration:
    oidcUrl: https://openzaak.example.nl
    oidcSecret: "<openzaak>"
    initContainer:
      enabled: true
    cronjob:
      enabled: false
  settings:
    allowedHosts: openzaak-nginx.podiumd.svc.cluster.local
    email:
      port: 587
      useTLS: true
    database:
      host: ""
      name: ""
      username: ""
      password: ""
    isHttps: false
  extraEnvVars:
    - name: DISABLE_2FA
      value: "True"
  persistence:
    size: 10Gi
    existingClaim: openzaak
  persistentVolume:
    volumeAttributeShareName: openzaak
  image:
    tag: "1.12.3"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  worker:
    resources:
      requests:
        cpu: 10m
        memory: 480Mi
      limits:
        cpu: 50m
        memory: 860Mi
  nameOverride: openzaak
  fullnameOverride: openzaak
  flower:
    enabled: false
  nginx:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 50m
        memory: 32Mi
  redis:
    nameOverride: openzaak-redis
    fullnameOverride: openzaak-redis
    master:
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 32Mi

opennotificaties:
  configuration:
    oidcUrl: https://opennotificaties.example.nl
    oidcSecret: "<opennotificaties>"
    initContainer:
      enabled: true
    cronjob:
      enabled: false
  settings:
    allowedHosts: opennotificaties.podiumd.svc.cluster.local
    maxRetries: 5
    retryBackoff: 3
    retryBackoffMax: 48
    email:
      port: 587
      useTLS: true
    cleanOldNotifications:
      enabled: true
      daysRetained: 30
      cronjob:
        schedule: "0 0 * * *"
        historyLimit: 1
    isHttps: false
  persistence:
    size: 10Gi
    existingClaim: opennotificaties
  persistentVolume:
    volumeAttributeShareName: opennotificaties
  image:
    tag: "1.6.0"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  worker:
    resources:
      requests:
        cpu: 50m
        memory: 386Mi
      limits:
        cpu: 200m
        memory: 640Mi
  nameOverride: opennotificaties
  fullnameOverride: opennotificaties
  flower:
    enabled: false
  rabbitmq:
    resources:
      requests:
        cpu: 300m
        memory: 256Mi
      limits:
        cpu: 512m
        memory: 384Mi
    nameOverride: opennotificaties-rabbitmq
    fullnameOverride: opennotificaties-rabbitmq
    auth:
      username: guest
      password: guest
      erlangCookie: SUPER-SECRET
  redis:
    nameOverride: opennotificaties-redis
    fullnameOverride: opennotificaties-redis
    master:
      resources: 
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 32Mi

objecten:
  configuration:
    oidcUrl: https://objecten.example.nl
    oidcSecret: "<objecten>"
  settings:
    allowedHosts: objecten.podiumd.svc.cluster.local
    email:
      port: 587
      useTLS: true
    isHttps: false
    disable2fa: true
  persistence:
    size: 10Gi
    existingClaim: objecten
  persistentVolume:
    volumeAttributeShareName: objecten
  image:
    tag: "2.4.1"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  worker:
    requests:
      cpu: 50m
      memory: 192Mi
    limits:
      cpu: 200m
      memory: 256Mi
  nameOverride: objecten
  fullnameOverride: objecten
  flower:
    enabled: false
  redis:
    nameOverride: objecten-redis
    fullnameOverride: objecten-redis
    master:
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 32Mi

objecttypen:
  configuration:
    oidcUrl: https://objecttypen.example.nl
    oidcSecret: "<objecttypen>"
  settings:
    allowedHosts: objecttypen.podiumd.svc.cluster.local
    email:
      port: 587
      useTLS: true
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false
  image:
    tag: "2.2.0"
  resources:
    requests:
      cpu: 10m
      memory: 160Mi
    limits:
      cpu: 1
      memory: 320Mi
  nameOverride: objecttypen
  fullnameOverride: objecttypen
  redis:
    nameOverride: objecttypen-redis
    fullnameOverride: objecttypen-redis
    master:
      resources:
        limits:
          cpu: 50m
          memory: 32Mi

openklant:
  configuration:
    oidcUrl: https://openklant.example.nl
    oidcSecret: "<openklant>"
  settings:
    allowedHosts: openklant.podiumd.svc.cluster.local
    email:
      port: 587
      useTLS: true
    isHttps: false
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false
  extraEnvVars:
    - name: DISABLE_2FA
      value: "True"
  image:
    tag: "2.1.0"
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 200m
      memory: 512Mi
  worker:
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 256Mi
  nameOverride: openklant
  fullnameOverride: openklant
  redis:
    nameOverride: openklant-redis
    fullnameOverride: openklant-redis
    master:
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 32Mi

openformulieren:
  configuration:
    oidcUrl: https://openformulieren.example.nl
    oidcSecret: "<openformulieren>"
  settings:
    allowedHosts: openformulieren-nginx.podiumd.svc.cluster.local
    email:
      port: 587
      useTLS: true
    isHttps: false
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false
  persistence:
    size: 10Gi
    existingClaim: openformulieren
    mediaMountSubpath: openformulieren/media
    privateMediaMountSubpath: openformulieren/private_media
  persistentVolume:
    volumeAttributeShareName: openformulieren
  image:
    tag: "2.6.7"
  resources:
    requests:
      cpu: 100m
      memory: 650Mi
    limits:
      cpu: 400m
      memory: 1.5Gi
  worker:
    livenessProbe:
      initialDelaySeconds: 120
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        cpu: 100m
        memory: 800Mi
  nameOverride: openformulieren
  fullnameOverride: openformulieren
  flower:
    enabled: false
  beat:
    resources:
      requests:
        cpu: 10m
        memory: 160Mi
    limits:
      cpu: 50m
      memory: 320Mi
  nginx:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 50m
        memory: 32Mi
  redis:
    nameOverride: openformulieren-redis
    fullnameOverride: openformulieren-redis
    master:
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 64Mi

openinwoner:
  configuration:
    oidcUrl: https://openinwoner.example.nl
    oidcSecret: "<openinwoner>"
  settings:
    allowedHosts: openinwoner-nginx.podiumd.svc.cluster.local
    email:
      port: 587
      useTLS: true
    isHttps: false
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false
  persistence:
    size: 10Gi
    existingClaim: openinwoner
  persistentVolume:
    volumeAttributeShareName: openinwoner
  image:
    tag: "1.20.0"
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1.5Gi
  worker:
    resources:
      requests:
        cpu: 200m
        memory: 640Mi
      limits:
        cpu: 400m
        memory: 1Gi
  nameOverride: openinwoner
  fullnameOverride: openinwoner
  nginx:
    config:
      clientMaxBodySize: 100M
    resources:
      requests:
        cpu: 30m
        memory: 8Mi
      limits:
        cpu: 60m
        memory: 16Mi
  redis:
    nameOverride: openinwoner-redis
    fullnameOverride: openinwoner-redis
    master:
      resources:
        requests:
          cpu: 20m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi
  elasticsearch:
    nameOverride: openinwoner-elasticsearch
    fullnameOverride: openinwoner-elasticsearch
    master:
      masterOnly: false
      resources:
        requests:
          cpu: 100m
          memory: 1.5Gi
        limits:
          cpu: 1
          memory: 2Gi
    data:
      replicaCount: 0
    coordinating:
      replicaCount: 0
      
kisselastic:
  kibanaDomain: kiss-kb-http.podiumd.svc.cluster.local:5601
  eck-operator:
    managedNamespaces:
      - podiumd

kiss:
  configuration:
    oidcUrl: https://kiss.example.nl
    oidcSecret: "<kiss>"

zac:
  configuration:
    oidcUrl: https://zac.example.nl
    oidcSecret: "<zac>"
  nameOverride: zac
  fullnameOverride: zac

clamav:
  image:
    tag: "1.3.1"
  nameOverride: clamav
  fullnameOverride: clamav
  resources:
    requests:
      cpu: 100m
      memory: 2Gi
    limits:
      cpu: 100m
      memory: 2Gi

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

httpRequestJob:
  intellijHttpClient:
    image:
      repository: jetbrains/intellij-http-client
      tag: "242.14146.16"
  jwtCli:
    image:
      repository: bitnami/jwt-cli
      tag: "6.1.0"
  alpine:
    image:
      repository: alpine
      tag: "3.20"
  nodeSelector: {}
