tags:
  formulier: true
  contact: false
  portaal: false
  zaak: false

global:
  configuration:
    enabled: true

keycloak:
  image:
    tag: "24.0.4-debian-12-r1"
  config:
    realmDisplayName: "PodiumD"
    realmFrontendUrl: ""
  keycloakConfigCli:
    enabled: true
    existingConfigmap: keycloak-config
  postgresql:
    enabled: false
  nameOverride: keycloak
  fullnameOverride: keycloak

openzaak:
  image:
    tag: "1.12.3"
  configuration:
    oidcUrl: "http://openzaak.podiumd.svc.cluster.local"
    oidcSecret: "<openzaak>"
    initContainer:
      enabled: true
    cronjob:
      enabled: false
  settings:
    isHttps: false
  resources:
    requests:
      cpu: 100m
      memory: 400Mi
  nameOverride: openzaak
  fullnameOverride: openzaak
  flower:
    enabled: false
  redis:
    nameOverride: openzaak-redis
    fullnameOverride: openzaak-redis

opennotificaties:
  image:
    tag: "1.6.0"
  configuration:
    oidcUrl: "http://opennotificaties.podiumd.svc.cluster.local"
    oidcSecret: "<opennotificaties>"
    initContainer:
      enabled: true
    cronjob:
      enabled: false
  settings:
    isHttps: false
  resources:
    requests:
      cpu: 10m
      memory: 200Mi
  nameOverride: opennotificaties
  fullnameOverride: opennotificaties
  flower:
    enabled: false
  rabbitmq:
    nameOverride: opennotificaties-rabbitmq
    fullnameOverride: opennotificaties-rabbitmq
    auth:
      username: guest
      password: guest
      erlangCookie: SUPER-SECRET
  redis:
    nameOverride: opennotificaties-redis
    fullnameOverride: opennotificaties-redis

objecten:
  image:
    tag: "2.3.1"
  configuration:
    oidcUrl: "http://objecten.podiumd.svc.cluster.local"
    oidcSecret: "<objecten>"
  settings:
    isHttps: false
    disable2fa: true
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
  nameOverride: objecten
  fullnameOverride: objecten
  flower:
    enabled: false
  redis:
    nameOverride: objecten-redis
    fullnameOverride: objecten-redis

objecttypen:
  image:
    tag: "2.1.2"
  configuration:
    oidcUrl: "http://objecttypen.podiumd.svc.cluster.local"
    oidcSecret: "<objecttypen>"
  settings:
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
  nameOverride: objecttypen
  fullnameOverride: objecttypen

openklant:
  image:
    tag: "2.0.0"
  configuration:
    oidcUrl: "http://openklant.podiumd.svc.cluster.local"
    oidcSecret: "<openklant>"
  settings:
    isHttps: false
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false
  resources:
    requests:
      cpu: 10m
      memory: 600Mi
  nameOverride: openklant
  fullnameOverride: openklant
  redis:
    nameOverride: openklant-redis
    fullnameOverride: openklant-redis

openformulieren:
  image:
    tag: "2.6.7"
  configuration:
    oidcUrl: "http://openformulieren.podiumd.svc.cluster.local"
    oidcSecret: "<openformulieren>"
  settings:
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false
  resources:
    requests:
      cpu: 10m
      memory: 600Mi
  nameOverride: openformulieren
  fullnameOverride: openformulieren
  flower:
    enabled: false
  beat:
    enabled: false
  redis:
    nameOverride: openformulieren-redis
    fullnameOverride: openformulieren-redis

openinwoner:
  image:
    tag: "1.16.5"
  configuration:
    oidcUrl: "http://openinwoner.podiumd.svc.cluster.local"
    oidcSecret: "<openinwoner>"
  settings:
    isHttps: false
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false
  resources:
    requests:
      cpu: 10m
      memory: 600Mi
  nameOverride: openinwoner
  fullnameOverride: openinwoner
  redis:
    nameOverride: openinwoner-redis
    fullnameOverride: openinwoner-redis
  elasticsearch:
    nameOverride: openinwoner-elasticsearch
    fullnameOverride: openinwoner-elasticsearch

kiss:
  configuration:
    oidcUrl: "http://kiss.podiumd.svc.cluster.local"
    oidcSecret: "<kiss>"

zac:
  configuration:
    oidcUrl: "http://zac.podiumd.svc.cluster.local"
    oidcSecret: "<zac>"

clamav:
  image:
    tag: "stable_base"
  Resources:
    limits:
      cpu: 100m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 2Gi
  # Ref: https://linux.die.net/man/5/clamd.conf
  clamdConfig: |
    ###############
    # General
    ###############
    DatabaseDirectory /data
    TemporaryDirectory /tmp
    LogTime yes
    # CUSTOM: Use pid file in tmp
    PidFile /tmp/clamd.pid
    LocalSocket /tmp/clamd.sock
    TCPSocket 3310
    Foreground yes
    ###############
    # Results
    ###############
    DetectPUA yes
    ExcludePUA NetTool
    ExcludePUA PWTool
    HeuristicAlerts yes
    Bytecode yes
    ###############
    # Scan
    ###############
    ScanPE yes
    DisableCertCheck yes
    ScanELF yes
    AlertBrokenExecutables yes
    ScanOLE2 yes
    ScanPDF yes
    ScanSWF yes
    ScanMail yes
    PhishingSignatures yes
    PhishingScanURLs yes
    ScanHTML yes
    ScanArchive yes
    ###############
    # Scan
    ###############
    MaxScanSize 150M
    MaxFileSize 30M
    MaxRecursion 10
    MaxFiles 15000
    MaxEmbeddedPE 10M
    MaxHTMLNormalize 10M
    MaxHTMLNoTags 2M
    MaxScriptNormalize 5M
    MaxZipTypeRcg 1M
    MaxPartitions 128
    MaxIconsPE 200
    PCREMatchLimit 10000
    PCRERecMatchLimit 10000
    ConcurrentDatabaseReload no
  ## Ref: https://linux.die.net/man/5/freshclam.conf
  freshclamConfig: |
    ###############
    # General
    ###############
    DatabaseDirectory /data
    UpdateLogFile /dev/stdout
    LogTime yes
    # CUSTOM: Use pid file in tmp
    PidFile /tmp/freshclam.pid
    # CUSTOM: Set defined user
    DatabaseOwner 2000
    ###############
    # Updates
    ###############
    DatabaseMirror database.clamav.net
    ScriptedUpdates yes
    NotifyClamd /etc/clamav/clamd.conf
    Bytecode yes
    TestDatabases no

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

httpRequestJob:
  intellijHttpClient:
    image:
      repository: "jetbrains/intellij-http-client"
      tag: "242.14146.16"
  jwtCli:
    image:
      repository: "bitnami/jwt-cli"
      tag: "6.1.0"
  alpine:
    image:
      repository: "alpine"
      tag: "3.20"
  nodeSelector: {}