configuration:
  enabled: true

keycloak:
  enabled: true
  nameOverride: keycloak
  fullnameOverride: keycloak
  postgresql:
    enabled: false
  keycloakConfigCli:
    enabled: true
    existingConfigmap: keycloak-config

openzaak:
  enabled: true
  nameOverride: open-zaak
  fullnameOverride: open-zaak
  image:
    tag: 1.12.3
  configuration:
    initContainer:
      enabled: true
    cronjob:
      enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 400Mi
  flower:
    enabled: false
  redis:
    nameOverride: open-zaak-redis
    fullnameOverride: open-zaak-redis

opennotificaties:
  enabled: true
  nameOverride: open-notificaties
  fullnameOverride: open-notificaties
  configuration:
    initContainer:
      enabled: true
    cronjob:
      enabled: false
  image:
    tag: 1.5.2
  resources:
    requests:
      cpu: 10m
      memory: 200Mi
  flower:
    enabled: false
  rabbitmq:
    nameOverride: open-notificaties-rabbitmq
    fullnameOverride: open-notificaties-rabbitmq
    auth:
      username: guest
      password: guest
      erlangCookie: SUPER-SECRET
  redis:
    nameOverride: open-notificaties-redis
    fullnameOverride: open-notificaties-redis

objecten:
  enabled: true
  nameOverride: objecten
  fullnameOverride: objecten
  image:
    tag: 2.3.1
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
  settings:
    disable2fa: true
  flower:
    enabled: false
  redis:
    nameOverride: objecten-redis
    fullnameOverride: objecten-redis

objecttypen:
  enabled: true
  nameOverride: objecttypen
  fullnameOverride: objecttypen
  image:
    tag: 2.1.2
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
  settings:
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false

openforms:
  enabled: true
  nameOverride: open-forms
  fullnameOverride: open-forms
  image:
    tag: 2.6.6
  resources:
    requests:
      cpu: 10m
      memory: 600Mi
  settings:
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false
  flower:
    enabled: false
  redis:
    nameOverride: open-forms-redis
    fullnameOverride: open-forms-redis

openklant:
  enabled: true
  nameOverride: open-klant
  fullnameOverride: open-klant
  image:
    tag: 2.0.0
  resources:
    requests:
      cpu: 10m
      memory: 600Mi
  settings:
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false
  redis:
    nameOverride: open-klant-redis
    fullnameOverride: open-klant-redis

openinwoner:
  enabled: true
  nameOverride: open-inwoner
  fullnameOverride: open-inwoner
  image:
    tag: 1.16.5
  resources:
    requests:
      cpu: 10m
      memory: 600Mi
  settings:
    twoFactorAuthentication:
      forceOtpAdmin: false
      patchAdmin: false
  redis:
    nameOverride: open-inwoner-redis
    fullnameOverride: open-inwoner-redis
  elasticsearch:
    nameOverride: open-inwoner-elasticsearch
    fullnameOverride: open-inwoner-elasticsearch

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

kiss:
  enabled: false

zac:
  enabled: false