adminUsername: "admin"
adminPassword: "admin"
root: "dc=dimpact,dc=org"

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

image:
  repository: bitnami/openldap
  tag: "2.6.9"
  pullPolicy: IfNotPresent

persistence:
  existingClaim: ""
  subpath: openldap

resources:
  requests:
    cpu: 10m
    memory: 50Mi

