replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: nginx
  tag: "1.25-alpine"
  pullPolicy: IfNotPresent

service:
  port: 8081

resources:
  limits:
    cpu: "0.5"
    memory: "256Mi"
  requests:
    cpu: "0.1"
    memory: "128Mi"

nginxCertsSecret: "podiumd-proxy-certs"

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

# Define common settings for all locations using YAML anchors
commonLocation: &commonLocation
  sslVerify: "off"
  hostHeader: "lab.api.mijniconnect.nl"

locations:
  bag:
    <<: *commonLocation
    targetUrl: "https://lab.api.mijniconnect.nl/iconnect/apihcbrp/actueel/v2/"
  brp:
    <<: *commonLocation
    targetUrl: "https://lab.api.mijniconnect.nl/iconnect/apihcbrp/actueel/prtcl/v2/personen"
  kvkSearch:
    <<: *commonLocation
    targetUrl: "https://lab.api.mijniconnect.nl/iconnect/apikvk/zoeken/v2/zoeken"
  kvkBasic:
    <<: *commonLocation
    targetUrl: "https://lab.api.mijniconnect.nl/iconnect/apikvk/basprof/v1/v1/basisprofielen"
  kvkBranch:
    <<: *commonLocation
    targetUrl: "https://lab.api.mijniconnect.nl/iconnect/apikvk/vesprof/v1/v1/vestigingsprofielen"
