### Create Kanaal autorisaties
POST {{notificatiesApi}}kanaal
Content-Type: application/json
Authorization: Bearer {{notificatiesJwt}}

{
  "naam": "autorisaties"
}

> {%
    client.test("Moet kanaal 'autorisaties' aanmaken", function () {
        client.assert(response.status === 201)
    });
%}

### Create Kanaal besluiten
POST {{notificatiesApi}}kanaal
Content-Type: application/json
Authorization: Bearer {{notificatiesJwt}}

{
  "naam": "besluiten",
  "filters": [
    "verantwoordelijke_organisatie",
    "besluittype"
  ]
}

> {%
    client.test("Moet kanaal 'besluiten' aanmaken", function () {
        client.assert(response.status === 201)
    });
%}

### Create Kanaal besluittypen
POST {{notificatiesApi}}kanaal
Content-Type: application/json
Authorization: Bearer {{notificatiesJwt}}

{
  "naam": "besluittypen",
  "filters": [
    "catalogus"
  ]
}

> {%
    client.test("Moet kanaal 'besluittypen' aanmaken", function () {
        client.assert(response.status === 201)
    });
%}

### Create Kanaal documenten
POST {{notificatiesApi}}kanaal
Content-Type: application/json
Authorization: Bearer {{notificatiesJwt}}

{
  "naam": "documenten",
  "filters": [
    "bronorganisatie",
    "informatieobjecttype",
    "vertrouwelijkheidaanduiding"
  ]
}

> {%
    client.test("Moet kanaal 'documenten' aanmaken", function () {
        client.assert(response.status === 201)
    });
%}

### Create Kanaal informatieobjecttypen
POST {{notificatiesApi}}kanaal
Content-Type: application/json
Authorization: Bearer {{notificatiesJwt}}

{
  "naam": "informatieobjecttypen",
  "filters": [
    "catalogus"
  ]
}

> {%
    client.test("Moet kanaal 'informatieobjecttypen' aanmaken", function () {
        client.assert(response.status === 201)
    });
%}

### Create Kanaal objecten
POST {{notificatiesApi}}kanaal
Content-Type: application/json
Authorization: Bearer {{notificatiesJwt}}

{
  "naam": "objecten",
  "filters": [
    "object_type"
  ]
}

> {%
    client.test("Moet kanaal 'objecten' aanmaken", function () {
        client.assert(response.status === 201)
    });
%}

### Create Kanaal statustypen
POST {{notificatiesApi}}kanaal
Content-Type: application/json
Authorization: Bearer {{notificatiesJwt}}

{
  "naam": "statustypen",
  "filters": [
    "catalogus"
  ]
}

> {%
    client.test("Moet kanaal 'statustypen' aanmaken", function () {
        client.assert(response.status === 201)
    });
%}

### Create Kanaal zaaktypen
POST {{notificatiesApi}}kanaal
Content-Type: application/json
Authorization: Bearer {{notificatiesJwt}}

{
  "naam": "zaaktypen",
  "filters": [
    "catalogus"
  ]
}

> {%
    client.test("Moet kanaal 'zaaktypen' aanmaken", function () {
        client.assert(response.status === 201)
    });
%}

### Create Kanaal zaken
POST {{notificatiesApi}}kanaal
Content-Type: application/json
Authorization: Bearer {{notificatiesJwt}}

{
  "naam": "zaken",
  "filters": [
    "bronorganisatie",
    "zaaktype",
    "vertrouwelijkheidaanduiding"
  ]
}

> {%
    client.test("Moet kanaal ´zaken' aanmaken", function () {
        client.assert(response.status === 201)
    });
%}
