# Default values for zaakafhandelcomponent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# contextUrl External URL to the zaakafhandelcomponent. (https://zaakafhandelcomponent.example.com)
contextUrl: ""

# db Configuration of database connection
db:
  host: "" # database.internal or 1.2.3.4
  name: ""
  user: ""
  password: ""

# auth Configuration of OpenID Connect
auth:
  server: "" # https://keycloak.example.com
  realm: ""
  # Client ID and secret as defined in the realm
  clientId: ""
  secret: ""

# ldap Configuration of ldap or ADFS connection
ldap:
  url: "" # ldap://openldap.internal:1389
  dn: ""  # ou=example-unit,dc=example,dc=org
  # Account to login into LDAP or ADFS with read rights
  user: ""
  password: ""

# gemeente Configuration gemeente
gemeente:
  code: ""
  naam: ""
  mail: ""

# mail Configuration email sending connection
mail:
  # API and secret key used for sending mail via mailjet (https://www.mailjet.com)
  mailjet:
    apiKey: ""
    secretKey: ""

# zgwApis Configuration of ZGW API's provider (Open Zaak)
zgwApis:
  url: "" # http://open-zaak.internal
  urlExtern: "" # https://open-zaak.example.com
  clientId: ""
  secret: ""

# notificationsSecretKey Configuration of the notifications receiving endpoint.
notificationsSecretKey: ""

# klantenApi Configuration of Klanten API provider (Open Klant)
klantenApi:
  url: "" # http://open-klant.internal
  clientId: ""
  secret: ""

# contactmomentenApi Configuration of Contactmomenten API provider (Open Klant)
contactmomentenApi:
  url: "" # http://open-klant.internal
  clientId: ""
  secret: ""

# objectenApi Configuration of the Objecten API provider (Overige Registraties)
objectenApi:
  url: "" # http://objecten.internal
  token: ""

# objecttypenApi Configuration of the Objecttypen API provider (Overige Registraties)
objecttypenApi:
  url: "" # http://objecttypen.internal
  token: ""

# brpApi Configuration of the BRP Api provider (Haal Centraal)
brpApi:
  url: "" # https://www.haalcentraal.nl/haalcentraal
  apiKey: ""

# kvkApi Configuration of the KVK API provider (KVK)
kvkApi:
  url: "" # https://developers.kvk.nl/test
  apiKey: ""

# bagApi Configuration of the BAG API provider (Kadaster)
bagApi:
  url: "" # https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2
  apiKey: ""

# vrlApi Configuration of the Referentielijsten & Selectielijst API provider (VNG)
vrlApi:
  url: "" # http://vng-referentielijsten.internal

# openForms Configuration of the Open Forms URL
openForms:
  url: "" # https://open-forms.example.com

# smartDocuments Configuration of the SmartDocuments connection
smartDocuments:
  url: "" # https://partners.smartdocuments.com
  authentication: ""
  fixedUserName: ""

# signalerenCronjob Configuration of the signaleren job
signalerenCronjob:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  restartPolicy: Never
  image:
    repository: curlimages/curl
    tag: latest
    pullPolicy: IfNotPresent
  imagePullSecrets: [ ]
  resources: { }
  podSecurityContext: { }
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]


# opentelemetry_zaakafhandelcomponent Overrides for opentelemetry
#opentelemetry_zaakafhandelcomponent:
#  sampler_type: "-off"
#  endpoint: "http://otel-collector:4317"


# maxFileSizeMB Maximum size (in Mega Bytes) of files that can be uploaded.
maxFileSizeMB: 80

# additionalAllowedFileTypes An optional list of additional file extensions that can be uploaded
# additionalAllowedFileTypes: aaa,bbb,ccc

# remoteDebug Enable Java remote debugging
remoteDebug: False

replicaCount: 1

image:
  repository: ghcr.io/infonl/zaakafhandelcomponent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  annotations: { }

ingress:
  enabled: false
  className: ""
  annotations: { }
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [ ]
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

backendConfig:
  enabled: false

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 100m
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: { }

tolerations: [ ]

affinity: { }

# Extra objects to deploy (value evaluated as a template)
extraDeploy: [ ]

opa:
  image:
    repository: openpolicyagent/opa
    tag: "edge-static"
    pullPolicy: IfNotPresent

solr:
  coreNames: [ "zac" ]
  persistence:
    size: 1Gi
  replicaCount: 1
  collectionReplicas: 1
  cloudBootstrap: false
  cloudEnabled: false
  customReadinessProbe:
    httpGet:
      port: http
      path: /solr/zac/admin/ping
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 15
    failureThreshold: 6
    successThreshold: 1
  customLivenessProbe:
    httpGet:
      port: http
      path: /solr/zac/admin/ping
    initialDelaySeconds: 40
    periodSeconds: 10
    timeoutSeconds: 15
    failureThreshold: 6
    successThreshold: 1
  service:
    ports:
      http: 80
  auth:
    enabled: false
  extraEnvVars:
    - name: ZK_CREATE_CHROOT
      value: "true"
  zookeeper:
    enabled: false

officeConverter:
  image:
    repository: ghcr.io/eugenmayer/kontextwork-converter
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 100m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 80
    annotations: { }
  podAnnotations: { }
  imagePullSecrets: [ ]
  podSecurityContext: { }
  # fsGroup: 2000
  securityContext: { }
    # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]

opentelemetry-collector:
  enabled: false
  mode: deployment
  replicaCount: 1
  presets:
    clusterMetrics:
      enabled: false
  ports:
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false
  config:
    receivers:
      prometheus: {}
      jaeger: {}
      zipkin: {}
    service:
      pipelines:
        traces:
          receivers:
            - otlp
        metrics: {}
        logs: {}
