# Default values for zaakafhandelcomponent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# contextUrl External URL to the zaakafhandelcomponent. (https://zaakafhandelcomponent.example.com)
contextUrl: ""

feature:
  bpmnSupport: false

# db Configuration of database connection
db:
  host: "" # database.internal or 1.2.3.4
  name: ""
  user: ""
  password: ""

# auth Configuration of OpenID Connect
auth:
  server: "" # https://keycloak.example.com
  realm: ""
  # Client ID and secret as defined in the realm
  clientId: ""
  secret: ""

# ldap Configuration of ldap or ADFS connection
ldap:
  url: "" # ldap://openldap.internal:1389
  dn: ""  # ou=example-unit,dc=example,dc=org
  # Account to login into LDAP or ADFS with read rights
  user: ""
  password: ""

# gemeente Configuration gemeente
gemeente:
  code: ""
  naam: ""
  mail: ""

# mail Configuration email sending connection
mail:
  # SMTP server and port will be required after phasing out mailjet
  smtp:
    server: "" # SMTP server host (for example localhost or in-v3.mailjet.com)
    port: "587" # port 587 for TLS, port 25 for relaying
    username: ""
    password: ""

# zgwApis Configuration of ZGW API's provider (Open Zaak)
zgwApis:
  url: "" # http://open-zaak.internal
  urlExtern: "" # https://open-zaak.example.com
  clientId: ""
  secret: ""

# notificationsSecretKey Configuration of the notifications receiving endpoint.
notificationsSecretKey: ""

# klantinteractiesApi Configuration of Klantinteracties API provider (Open Klant)
klantinteractiesApi:
  url: "" # http://open-klant.internal
  token: ""

# objectenApi Configuration of the Objecten API provider (Overige Registraties)
objectenApi:
  url: "" # http://objecten.internal
  token: ""

# objecttypenApi Configuration of the Objecttypen API provider (Overige Registraties)
objecttypenApi:
  url: "" # http://objecttypen.internal
  token: ""

# brpApi Configuration of the BRP Api provider (Haal Centraal)
brpApi:
  url: "" # https://www.haalcentraal.nl/haalcentraal
  apiKey: ""

# kvkApi Configuration of the KVK API provider (KVK)
kvkApi:
  url: "" # https://developers.kvk.nl/test
  apiKey: ""

# bagApi Configuration of the BAG API provider (Kadaster)
bagApi:
  url: "" # https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2
  apiKey: ""

# openForms Configuration of the Open Forms URL
openForms:
  url: "" # https://open-forms.example.com

# smartDocuments Configuration of the SmartDocuments connection
smartDocuments:
  url: "" # https://partners.smartdocuments.com
  authentication: ""
  fixedUserName: ""

# signalerenCronjob Configuration of the signaleren cron job
signalerenCronjob:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  restartPolicy: Never
  image:
    repository: curlimages/curl
    tag: latest
    pullPolicy: IfNotPresent
  imagePullSecrets: [ ]
  resources: { }
  podSecurityContext: { }
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]

# deleteSignaleringenCronjob Configuration of the delete signaleringen cron job
deleteSignaleringenCronjob:
  deleteOlderThanDays: "14"
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  restartPolicy: Never
  image:
    repository: curlimages/curl
    tag: latest
    pullPolicy: IfNotPresent
  imagePullSecrets: [ ]
  resources: { }
  podSecurityContext: { }
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]

# maxFileSize Maximum size (in Mega Bytes) of files that can be uploaded.
maxFileSize: 80

# additionalAllowedFileTypes An optional list of additional file extensions that can be uploaded
# additionalAllowedFileTypes: aaa,bbb,ccc

# remoteDebug Enable Java remote debugging
remoteDebug: False

# replicaCount the number of replicas to run
replicaCount: 1

# image the image parameters to use
image:
  repository: ghcr.io/infonl/zaakafhandelcomponent
  pullPolicy: IfNotPresent

# imagePullSecrets specifies image pull secrets
imagePullSecrets: [ ]

# nameOverride name to use
nameOverride: ""

# fullnameOverride fullname to use
fullnameOverride: ""

# serviceAccount service account parameters
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# podAnnotations pod specific annotations
podAnnotations: { }

# podSecurityContext pod specific security context
podSecurityContext: { }

# securityContext generic security context
securityContext: { }

# service service specifications
service:
  type: ClusterIP
  port: 80
  annotations: { }

# ingress ingress specifications
ingress:
  enabled: false
  className: ""
  annotations: { }
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [ ]

# backendConfig Use by GCP Ingress
backendConfig:
  enabled: false

# resources specify resources limits and requests
resources:
  requests:
    cpu: 100m
    memory: 1Gi

# autoscaling set autoscaling parameters
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# nodeSelector set node selector parameters
nodeSelector: { }

# tolerations set toleration parameters
tolerations: [ ]

# affinity set affinity parameters
affinity: { }

# Extra objects to deploy (value evaluated as a template)
extraDeploy: [ ]

# opa provision the opa sidecar container
opa:
  image:
    repository: openpolicyagent/opa
    tag: "edge-static"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 10m
      memory: 20Mi

# solr provision the SOLR subchart
solr:
  nameOverride: zac-solr
  fullnameOverride: zac-solr
  coreNames: [ "zac" ]
  persistence:
    size: 1Gi
    existingClaim: zac-solr
  persistentVolume:
    volumeAttributeShareName: zac-solr
    volumeAttributeResourceGroup: ""
    nodeStageSecretRefName: ""
    nodeStageSecretRefNamespace: ""
  replicaCount: 1
  collectionReplicas: 1
  cloudBootstrap: false
  cloudEnabled: false
  customReadinessProbe:
    httpGet:
      port: http
      path: /solr/zac/admin/ping
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 15
    failureThreshold: 6
    successThreshold: 1
  customLivenessProbe:
    httpGet:
      port: http
      path: /solr/zac/admin/ping
    initialDelaySeconds: 40
    periodSeconds: 10
    timeoutSeconds: 15
    failureThreshold: 6
    successThreshold: 1
  service:
    ports:
      http: 80
  auth:
    enabled: false
  extraEnvVars:
    - name: ZK_CREATE_CHROOT
      value: "true"
  zookeeper:
    enabled: false

# officeConverter provision the office converter deployment
officeConverter:
  image:
    repository: ghcr.io/eugenmayer/kontextwork-converter
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 80
    annotations: { }
  podAnnotations: { }
  imagePullSecrets: [ ]
  podSecurityContext: { }
  securityContext: { }
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]

# opentelemetryCollector provision the opentelemetry collector sub chart
opentelemetryCollector:
  nameOverride: zac-opentelemetry-collector
  fullnameOverride: zac-opentelemetry-collector
  samplerType: "off"
  mode: deployment
  replicaCount: 1
  presets:
    clusterMetrics:
      enabled: false
  ports:
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false
  config:
    receivers:
      prometheus: {}
      jaeger: {}
      zipkin: {}
    service:
      pipelines:
        traces:
          receivers:
            - otlp
        metrics: {}
        logs: {}
