{
 "title": "Monitoring en logging PodiumD",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "App",
    "label": "Component",
    "query": {}
   },
   {
    "name": "Subapp",
    "label": "Subcomponent",
    "query": {}
   },
   { "name": "LogLevel", "label": "Log niveau", "query": "warn,error" },
   {
    "name": "Methode",
    "label": "HTTP methode",
    "query": "GET,POST,PUT,DELETE,PATCH,HEAD,OPTIONS,TRACE,CONNECT"
   },
   {
    "name": "http_code",
    "label": "HTTP code",
    "query": "200,201,204,301,302,304,400,401,403,404,405,429,500,502,503,504"
   },
   { "name": "search", "label": "Zoeken" },
   { "name": "Dashboard_versie", "query": "1.1" },
   {
    "name": "excluded_log_levels",
    "query": "DEBUG, INFO, maykin, maykinmedia, Datadog, sentry, GET / =>, GET /_health/, GET /admin, GET /api/ent, WARN, uWSGI, NO MERCY"
   }
  ]
 },
 "panels": [
  {
   "title": "Totaal logs component: \"$App\" historisch ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({app=~\"$Subapp\"} [$__interval]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Keten formulieren -> e-Suite",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alle inzendingen en niet-succesvolle inzendingen",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({app=\"openformulieren-nginx\"} |~ \"POST /api/v2/submissions/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/_complete\" |~ `HTTP/1.1\\\" 200` [$__range]))",
       "legendFormat": "Alle inzendingen"
      },
      {
       "expr": "sum(count_over_time({app=\"openformulieren-worker\"} |~ \"\\\"public_reference\\\":\\\"OF-[0-9a-zA-Z]{6}\\\"\" |~ \"/api/v2/objects/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\" [$__range]))",
       "legendFormat": "Inzending met succes (zaak?)"
      }
     ]
    },
    {
     "title": "Succesvol ingezonden formulieren OF-nummers",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum by (of_id) (\r\n  count_over_time(\r\n    {app=\"openformulieren-worker\"} \r\n    |~ \"\\\"public_reference\\\":\\\"OF-[0-9a-zA-Z]{6}\\\"\"\r\n    |~ \"/api/v2/objects/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\"\r\n    | regexp `.*(?P<of_id>OF-[A-Za-z0-9]{6}).*` \r\n    [$__interval]\r\n  )\r\n)",
       "legendFormat": "{{of_id}}"
      },
      {
       "expr": "sum (\r\n  count_over_time(\r\n    {app=\"openformulieren-worker\"} \r\n    |~ \"\\\"public_reference\\\":\\\"OF-[0-9a-zA-Z]{6}\\\"\"\r\n    |~ \"/api/v2/objects/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\" \r\n    | regexp `.*(?P<of_id>OF-[A-Za-z0-9]{6}).*`\r\n    [$__interval]\r\n  )\r\n)",
       "legendFormat": "Totaal"
      }
     ]
    },
    {
     "title": "Keten formulieren -> e-Suite",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time ({app=\"opennotificaties\"} |~ `POST /api/v1/notificaties` |~ \"HTTP/1.1 201\" [$__range]))",
       "legendFormat": "Notificatie"
      },
      {
       "expr": "sum(count_over_time({app=\"objecten\"} |~ \"POST /api/v2/objects\" |~ \"HTTP/1.1 201\" [$__range]))",
       "legendFormat": "Objecten"
      },
      {
       "expr": "sum(count_over_time ({app=\"openformulieren-nginx\"} |~ \"POST /api/v2/submissions/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/_complete\" |~ `HTTP/1.1\\\" 200` [$__range]))",
       "legendFormat": "Inzending formulier"
      },
      {
       "expr": "sum(count_over_time(\r\n        {app=\"openformulieren-worker\"}  \r\n        |~ \"/zgw-apis-provider/drc/api/v1/enkelvoudiginformatieobjecten/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\"\r\n        |~ `\"public_reference\":\"OF-[0-9a-zA-Z]{6}\"`\r\n        |~ \".pdf\"\r\n        [$__range]))\r\n",
       "legendFormat": "DRC"
      },
      {
       "expr": "sum(\r\n    count_over_time({app=\"openformulieren-worker\"}  |~ `\"public_reference\":\"OF-[0-9a-zA-Z]{6}\"` |~ \"/api/v2/objects/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\" [$__range]))",
       "legendFormat": "Inzending succes"
      }
     ]
    },
    {
     "title": "Alle ingezonden formulier namen",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "sum by (formulier) (count_over_time({app=\"openformulieren-nginx\"} \r\n|~ `https?://[^/\\s]+/([^/\\s]+)` \r\n|~ \"POST /api/v2/submissions/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/_complete\" \r\n| regexp `https?://(?P<url>[^/\\s]+)/(?P<formulier>[^/\\s]+)` \r\n!= \"maykinmedia\" != \"maykin\" != \"sentry\" [$__interval])) ",
       "legendFormat": "{{formulier}}"
      },
      {
       "expr": "sum (count_over_time({app=\"openformulieren-nginx\"} \r\n|~ `https?://[^/\\s]+/([^/\\s]+)` \r\n|~ \"POST /api/v2/submissions/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/_complete\" \r\n| regexp `https?://(?P<url>[^/\\s]+)/(?P<formulier>[^/\\s]+)` \r\n!= \"maykinmedia\" != \"maykin\" != \"sentry\" [$__interval])) ",
       "legendFormat": "Totaal"
      }
     ]
    },
    {
     "title": "HTTP codes component: \"$App\"",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 71 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({app=~\"$Subapp\"} |~ \"HTTP/1.1\\\" 5[0-9]{2}\" [$__interval]))",
       "legendFormat": "HTTP5x (Kritisch)"
      },
      {
       "expr": "sum(count_over_time({app=~\"$Subapp\"} |~ \"HTTP/1.1\\\" 4[0-9]{2}\" [$__interval]))",
       "legendFormat": "HTTP4x (Error)"
      },
      {
       "expr": "sum(count_over_time({app=~\"$Subapp\"} |~ \"HTTP/1.1\\\" 3[0-9]{2}\" [$__interval]))",
       "legendFormat": "HTTP3x (Redirect)"
      },
      {
       "expr": "sum(\r\n  count_over_time({app=~\"$Subapp\"} |~ \"HTTP/1.1\\\" 2[0-9]{2}\" [$__interval]))",
       "legendFormat": "HTTP2x (Succes)"
      }
     ]
    },
    {
     "title": "Alle ingezonden formulier namen en OF-nummers historisch",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 71 },
     "targets": [
      {
       "expr": "sum by (formulier) (count_over_time({app=\"openformulieren-nginx\"}\r\n|~ `https?://[^/\\s]+/([^/\\s]+)` \r\n|~ \"POST /api/v2/submissions/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/_complete\" \r\n| regexp `https?://(?P<url>[^/\\s]+)/(?P<formulier>[^/\\s]+)`  \r\n[$__interval])) ",
       "legendFormat": "{{formulier}}"
      },
      {
       "expr": "sum by (of_id) (\r\n  count_over_time(\r\n    {app=\"openformulieren-worker\"} \r\n    |~ \"\\\"public_reference\\\":\\\"OF-[0-9a-zA-Z]{6}\\\"\"\r\n    |~ \"/api/v2/objects/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\" \r\n    | regexp `.*(?P<of_id>OF-[A-Za-z0-9]{6}).*`\r\n    [$__interval]\r\n  )\r\n)",
       "legendFormat": "{{of_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alle logs voor component: \"$App\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs component: $App",
     "type": "logs",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{app=~\"$Subapp\"}  |~ \"(?i)$search\" |~ \"(?i)$Methode\" |~ \"(?i)$LogLevel\" !~ `$excluded_log_levels` != `HTTP/1.1\" 0 \"`",
       "maxLines": 100
      }
     ]
    }
   ]
  },
  {
   "title": "Logs met ALLEEN een HTTP code. Gekozen HTTP code: \"$http_code\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs met HTTP code: $http_code",
     "type": "logs",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{app=~\"$Subapp\"} !~ `$excluded_log_levels` |~ \"(?i)$search\" |~ `HTTP/1.1[\\\" ]*$http_code` != `HTTP/1.1\" 0 \"` |~ \"(?i)$Methode\" |~ \"(?i)$LogLevel\"",
       "maxLines": 100
      }
     ]
    }
   ]
  },
  {
   "title": "Logs inzending formulieren met OF-nummer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs inzending formulieren",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 120 },
     "targets": [
      {
       "expr": "{app=\"openformulieren-worker\"} |~ \"\\\"public_reference\\\":\\\"OF-[0-9a-zA-Z]{6}\\\"\" ",
       "maxLines": 100
      }
     ]
    }
   ]
  },
  {
   "title": "Logs formulieren",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Naam van formulier",
     "type": "logs",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "{app=\"openformulieren-nginx\"} \r\n|~ `https?://[^/\\s]+/([^/\\s]+)` \r\n|~ \"POST /api/v2/submissions/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/_complete\" \r\n| regexp `POST /api/v2/submissions/(?P<id>[0-9a-fA-F-]+)`\r\n| regexp `https?://(?P<url>[^/\\s]+)/(?P<formulier>[^/\\s]+)` \r\n| line_format \"URL: https://{{.url}}/{{.formulier}}, Formulier: {{.formulier}}, SubmissionID: {{.id}}\"\r\n!~ `$excluded_log_levels`",
       "maxLines": 100
      }
     ]
    }
   ]
  }
 ]
}