apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podiumd-proxy.fullname" . }}
  labels:
    app: {{ include "podiumd-proxy.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "podiumd-proxy.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "podiumd-proxy.name" . }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-certs
          mountPath: /etc/nginx/certs
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: /_health/
            port: {{ .Values.service.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /_health/
            port: {{ .Values.service.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "podiumd-proxy.fullname" . }}-nginx-config
      - name: nginx-certs
        secret:
          secretName: {{ .Values.nginxCertsSecret }}
