apiVersion: v1
kind: Service
metadata:
  name: {{ include "vrl.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "vrl.name" . }}
    {{- include "vrl.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "vrl.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: http

