{{- if .Values.promtail.enabled }}
promtail:
  config:
    logLevel: {{ .Values.promtail.config.logLevel | quote }}
    # Publish data to Loki using the URL that includes the release name
    clients:
      - url: http://{{ .Release.Name }}-gateway/loki/api/v1/push
        tenant_id: {{ index .Values.promtail.config.clients 0 "tenant_id" }}
  image:
    registry: {{ .Values.promtail.image.registry | quote }}
    repository: {{ .Values.promtail.image.repository | quote }}
    tag: {{ .Values.promtail.image.tag | quote }}
  resources:
    requests:
      cpu: {{ .Values.promtail.resources.requests.cpu | quote }}
      memory: {{ .Values.promtail.resources.requests.memory | quote }}
    limits:
      cpu: {{ .Values.promtail.resources.limits.cpu | quote }}
      memory: {{ .Values.promtail.resources.limits.memory | quote }}
{{- end }}
