apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flowable-ui.fullname" . }}
  labels:
    {{- include "flowable-ui.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_DRIVER-CLASS-NAME: {{ .Values.database.datasourceDriverClassName | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.database.datasourceUrl | quote }}