apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowable-ui.fullname" . }}
  labels:
    {{- include "flowable-ui.labels" . | nindent 4 }}
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.user | quote }}

