name: Test values.yaml with podiumd helm chart

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - 'feature/**'

jobs:
  Powershell:
    runs-on: ubuntu-latest
    env:
      branch_name: ${{ github.head_ref || github.ref_name }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: bake deployment
      id: bake
      uses: azure/k8s-bake@v3
      with:
        renderEngine: "helm"
        releaseName: github-test
        helmChart: 'charts/podiumd'        
        namespace: podiumd
        
