apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zaakafhandelcomponent.fullname" . }}
  labels:
    {{- include "zaakafhandelcomponent.labels" . | nindent 4 }}
data:
  AUTH_REALM: {{ required "Valid .Values.auth.realm entry required!" .Values.auth.realm }}
  AUTH_RESOURCE: {{ required "Valid .Values.auth.clientId entry required!" .Values.auth.clientId }}
  AUTH_SERVER: {{ required "Valid .Values.auth.server entry required!" .Values.auth.server }}
  BAG_API_CLIENT_MP_REST_URL: {{ required "Valid .Values.bagApi.url entry required!" .Values.bagApi.url }}
  BRP_API_CLIENT_MP_REST_URL: {{ required "Valid .Values.brpApi.url entry required!" .Values.brpApi.url }}
  CONTEXT_URL: {{ required "Valid .Values.contextUrl entry required!" .Values.contextUrl }}
  DB_HOST: {{ required "Valid .Values.db.host entry required!" .Values.db.host }}
  DB_NAME: {{ required "Valid .Values.db.name entry required!" .Values.db.name }}
  DB_USER: {{ required "Valid .Values.db.user entry required!" .Values.db.user }}
  FEATURE_FLAG_BPMN_SUPPORT: {{ required "Valid .Values.feature.bpmnSupport entry required!" .Values.feature.bpmnSupport | quote }}
  GEMEENTE_CODE: {{ required "Valid .Values.gemeente.code entry required!" .Values.gemeente.code  | quote }}
  GEMEENTE_NAAM: {{ required "Valid .Values.gemeente.naam entry required!" .Values.gemeente.naam }}
  GEMEENTE_MAIL: {{ required "Valid .Values.gemeente.mail entry required!" .Values.gemeente.mail }}
  KLANTINTERACTIES_API_CLIENT_MP_REST_URL: {{ required "Valid .Values.klantinteractiesApi.url entry required!" .Values.klantinteractiesApi.url }}
  KVK_API_CLIENT_MP_REST_URL: {{ required "Valid .Values.kvkApi.url entry required!" .Values.kvkApi.url }}
  LDAP_DN: {{ required "Valid .Values.ldap.dn entry required!" .Values.ldap.dn }}
  LDAP_URL: {{ required "Valid .Values.ldap.url entry required!" .Values.ldap.url }}
  LDAP_USER: {{ required "Valid .Values.ldap.user entry required!" .Values.ldap.user }}
  {{- if .Values.additionalAllowedFileTypes }}
  ADDITIONAL_ALLOWED_FILE_TYPES: {{ .Values.additionalAllowedFileTypes }}
  {{- end}}
  MAX_FILE_SIZE_MB: {{ .Values.maxFileSize | quote }}
  MP_HEALTH_EMPTY_LIVENESS_CHECKS_STATUS: DOWN
  MP_HEALTH_EMPTY_READINESS_CHECKS_STATUS: DOWN
  OBJECTS_API_CLIENT_MP_REST_URL: {{ required "Valid .Values.objectenApi.url entry required!" .Values.objectenApi.url }}
  OBJECTTYPES_API_CLIENT_MP_REST_URL: {{ required "Valid .Values.objecttypenApi.url entry required!" .Values.objecttypenApi.url }}
  OFFICE_CONVERTER_CLIENT_MP_REST_URL: {{ printf "http://%s-office-converter.%s" (include "zaakafhandelcomponent.fullname" .) .Release.Namespace }}
  OPA_API_CLIENT_MP_REST_URL: http://localhost:8181
  OPEN_FORMS_URL: {{ required "Valid .Values.openForms.url entry required!" .Values.openForms.url }}
  SIGNALERINGEN_DELETE_OLDER_THAN_DAYS: {{ required "Valid .Values.deleteSignaleringenCronjob.deleteOlderThanDays entry required!" .Values.deleteSignaleringenCronjob.deleteOlderThanDays | quote }}
  SMTP_PORT: {{ required "Valid .Values.mail.smtp.port entry required!" .Values.mail.smtp.port | quote }}
  SMTP_SERVER: {{ required "Valid .Values.mail.smtp.server entry required!" .Values.mail.smtp.server }}
  SUBSYSTEM_OPENTELEMETRY__SAMPLER_TYPE: {{ .Values.opentelemetryCollector.samplerType | quote }}
  SUBSYSTEM_OPENTELEMETRY__ENDPOINT: {{ .Values.opentelemetryCollector.endpoint | default (printf "http://%s-opentelemetry-collector:4317" .Release.Name) }}
  SD_CLIENT_MP_REST_URL: {{ required "Valid .Values.smartDocuments.url entry required!" .Values.smartDocuments.url }}
  {{- if .Values.smartDocuments.fixedUserName }}
  SD_FIXED_USER_NAME: {{ .Values.smartDocuments.fixedUserName }}
  {{- end}}
  SOLR_URL: {{ printf "http://%s-solr.%s" (include "zaakafhandelcomponent.fullname" .) .Release.Namespace }}
  TZ: Europe/Amsterdam
  ZGW_API_CLIENT_MP_REST_URL: {{ required "Valid .Values.zgwApis.url entry required!" .Values.zgwApis.url }}
  ZGW_API_CLIENTID: {{ required "Valid .Values.zgwApis.clientId entry required!" .Values.zgwApis.clientId }}
  ZGW_API_URL_EXTERN: {{ required "Valid .Values.zgwApis.urlExtern entry required!" .Values.zgwApis.urlExtern }}
