apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "zaakafhandelcomponent.fullname" . }}-delete-signaleringen
  labels:
    {{- include "zaakafhandelcomponent.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.deleteSignaleringenCronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.deleteSignaleringenCronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.deleteSignaleringenCronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "zaakafhandelcomponent.labels" . | nindent 12 }}
        spec:
          {{- with .Values.deleteSignaleringenCronjob.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "zaakafhandelcomponent.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.deleteSignaleringenCronjob.podSecurityContext | nindent 12 }}
          restartPolicy: {{ .Values.deleteSignaleringenCronjob.restartPolicy }}
          containers:
            - name: {{ include "zaakafhandelcomponent.fullname" . }}-delete-signaleringen
              image: "{{ .Values.deleteSignaleringenCronjob.image.repository }}:{{ .Values.deleteSignaleringenCronjob.image.tag }}"
              imagePullPolicy: {{ .Values.deleteSignaleringenCronjob.image.pullPolicy }}
              resources:
                {{- toYaml .Values.deleteSignaleringenCronjob.resources | nindent 16 }}
              args:
                - -X DELETE
                - {{ printf "http://%s.%s/rest/admin/signaleringen/delete-old" (include "zaakafhandelcomponent.fullname" .) .Release.Namespace }}
          {{- with .Values.deleteSignaleringenCronjob.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deleteSignaleringenCronjob.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deleteSignaleringenCronjob.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
