apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zaakafhandelcomponent.fullname" . }}-office-converter
  labels:
    {{- include "zaakafhandelcomponent.office-converter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "zaakafhandelcomponent.office-converter.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.officeConverter.replicas }}
  template:
    metadata:
      annotations:
      {{- with .Values.officeConverter.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zaakafhandelcomponent.office-converter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.officeConverter.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zaakafhandelcomponent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.officeConverter.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-office-converter
          securityContext:
            {{- toYaml .Values.officeConverter.securityContext | nindent 12 }}
          image: "{{ .Values.officeConverter.image.repository }}:{{ .Values.officeConverter.image.tag }}"
          imagePullPolicy: {{ .Values.officeConverter.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          resources:
            {{- toYaml .Values.officeConverter.resources | nindent 12 }}
      {{- with .Values.officeConverter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.officeConverter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.officeConverter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
