apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zaakafhandelcomponent.fullname" . }}
  labels:
    {{- include "zaakafhandelcomponent.labels" . | nindent 4 }}
stringData:
  AUTH_SECRET: "{{ required "Valid .Values.auth.secret entry required!" .Values.auth.secret }}"
  BAG_API_KEY: "{{ required "Valid .Values.bagApi.apiKey entry required!" .Values.bagApi.apiKey }}"
  BRP_API_KEY: "{{ required "Valid .Values.brpApi.apiKey entry required!" .Values.brpApi.apiKey }}"
  CONTACTMOMENTEN_API_SECRET: "{{ required "Valid .Values.contactmomentenApi.secret entry required!" .Values.contactmomentenApi.secret }}"
  DB_PASSWORD: "{{ required "Valid .Values.db.password entry required!" .Values.db.password }}"
  KLANTINTERACTIES_API_TOKEN: "{{ required "Valid .Values.klantenApi.token entry required!" .Values.klantenApi.token }}"
  KVK_API_KEY: "{{ required "Valid .Values.kvkApi.apiKey entry required!" .Values.kvkApi.apiKey }}"
  LDAP_PASSWORD: "{{ required "Valid .Values.ldap.password entry required!" .Values.ldap.password }}"
  OBJECTS_API_TOKEN: "{{ required "Valid .Values.objectenApi.token entry required!" .Values.objectenApi.token }}"
  OBJECTTYPES_API_TOKEN: "{{ required "Valid .Values.objecttypenApi.token entry required!" .Values.objecttypenApi.token }}"
  OPEN_NOTIFICATIONS_API_SECRET_KEY: "{{ required "Valid .Values.notificationsSecretKey entry required!" .Values.notificationsSecretKey }}"
  SD_AUTHENTICATION: "{{ required "Valid .Values.smartDocuments.authentication entry required!" .Values.smartDocuments.authentication }}"
  SMTP_PASSWORD: "{{ .Values.mail.smtp.password }}"
  SMTP_USERNAME: "{{ .Values.mail.smtp.username }}"
  ZGW_API_SECRET: "{{ required "Valid .Values.zgwApis.secret entry required!" .Values.zgwApis.secret }}"


